export type LookupEntry = {
  canonical: string;
  aliases: string[];
};

export const LOCATION_LOOKUP_ENTRIES: LookupEntry[] = [
  { canonical: "서울시", aliases: ["서울특별시", "서울시", "서울"] },
  { canonical: "부산시", aliases: ["부산광역시", "부산시", "부산"] },
  { canonical: "대구시", aliases: ["대구광역시", "대구시", "대구"] },
  { canonical: "인천시", aliases: ["인천광역시", "인천시", "인천"] },
  { canonical: "광주시", aliases: ["광주광역시", "광주시", "광주"] },
  { canonical: "대전시", aliases: ["대전광역시", "대전시", "대전"] },
  { canonical: "울산시", aliases: ["울산광역시", "울산시", "울산"] },
  { canonical: "세종시", aliases: ["세종특별자치시", "세종시", "세종"] },
  { canonical: "경기", aliases: ["경기도", "경기"] },
  { canonical: "강원", aliases: ["강원특별자치도", "강원도", "강원"] },
  { canonical: "충북", aliases: ["충청북도", "충북"] },
  { canonical: "충남", aliases: ["충청남도", "충남"] },
  { canonical: "전북", aliases: ["전북특별자치도", "전라북도", "전북"] },
  { canonical: "전남", aliases: ["전라남도", "전남"] },
  { canonical: "경북", aliases: ["경상북도", "경북"] },
  { canonical: "경남", aliases: ["경상남도", "경남"] },
  { canonical: "제주", aliases: ["제주특별자치도", "제주도", "제주"] },
  { canonical: "수원시", aliases: ["수원시", "수원"] },
  { canonical: "강남구", aliases: ["강남구"] },
  { canonical: "서초구", aliases: ["서초구"] },
  { canonical: "송파구", aliases: ["송파구"] },
  { canonical: "부산진구", aliases: ["부산진구"] },
  { canonical: "가락동", aliases: ["가락동"] },
  { canonical: "삼성동", aliases: ["삼성동"] },
  { canonical: "우면동", aliases: ["우면동"] },
  { canonical: "연지동", aliases: ["연지동"] },
  { canonical: "삼성역", aliases: ["삼성역"] },
  { canonical: "양재역", aliases: ["양재역"] },
  { canonical: "잠실", aliases: ["잠실", "잠실역"] },
  { canonical: "성남시", aliases: ["성남시", "성남"] },
  { canonical: "용인시", aliases: ["용인시", "용인"] },
  { canonical: "고양시", aliases: ["고양시", "고양"] },
  { canonical: "부천시", aliases: ["부천시", "부천"] },
  { canonical: "안산시", aliases: ["안산시", "안산"] },
  { canonical: "안양시", aliases: ["안양시", "안양"] },
  { canonical: "화성시", aliases: ["화성시", "화성"] },
  { canonical: "평택시", aliases: ["평택시", "평택"] },
  { canonical: "의정부시", aliases: ["의정부시", "의정부"] },
  { canonical: "시흥시", aliases: ["시흥시", "시흥"] },
  { canonical: "파주시", aliases: ["파주시", "파주"] },
  { canonical: "김포시", aliases: ["김포시", "김포"] },
  { canonical: "춘천시", aliases: ["춘천시", "춘천"] },
  { canonical: "원주시", aliases: ["원주시", "원주"] },
  { canonical: "강릉시", aliases: ["강릉시", "강릉"] },
  { canonical: "청주시", aliases: ["청주시", "청주"] },
  { canonical: "충주시", aliases: ["충주시", "충주"] },
  { canonical: "제천시", aliases: ["제천시", "제천"] },
  { canonical: "천안시", aliases: ["천안시", "천안"] },
  { canonical: "아산시", aliases: ["아산시", "아산"] },
  { canonical: "서산시", aliases: ["서산시", "서산"] },
  { canonical: "공주시", aliases: ["공주시", "공주"] },
  { canonical: "보령시", aliases: ["보령시", "보령"] },
  { canonical: "전주시", aliases: ["전주시", "전주"] },
  { canonical: "군산시", aliases: ["군산시", "군산"] },
  { canonical: "익산시", aliases: ["익산시", "익산"] },
  { canonical: "목포시", aliases: ["목포시", "목포"] },
  { canonical: "여수시", aliases: ["여수시", "여수"] },
  { canonical: "순천시", aliases: ["순천시", "순천"] },
  { canonical: "나주시", aliases: ["나주시", "나주"] },
  { canonical: "포항시", aliases: ["포항시", "포항"] },
  { canonical: "경주시", aliases: ["경주시", "경주"] },
  { canonical: "구미시", aliases: ["구미시", "구미"] },
  { canonical: "안동시", aliases: ["안동시", "안동"] },
  { canonical: "창원시", aliases: ["창원시", "창원"] },
  { canonical: "진주시", aliases: ["진주시", "진주"] },
  { canonical: "김해시", aliases: ["김해시", "김해"] },
  { canonical: "양산시", aliases: ["양산시", "양산"] },
  { canonical: "거제시", aliases: ["거제시", "거제"] },
  { canonical: "제주시", aliases: ["제주시"] },
  { canonical: "서귀포시", aliases: ["서귀포시", "서귀포"] },
];

export const COMPANY_LOOKUP_ENTRIES: LookupEntry[] = [
  { canonical: "삼성전자", aliases: ["삼성전자"] },
  { canonical: "삼성SDS", aliases: ["삼성SDS", "삼성 SDS"] },
  { canonical: "삼성물산", aliases: ["삼성물산"] },
  { canonical: "삼성카드", aliases: ["삼성카드"] },
  { canonical: "삼성증권", aliases: ["삼성증권"] },
  { canonical: "LG전자", aliases: ["LG전자", "엘지전자"] },
  { canonical: "현대자동차", aliases: ["현대자동차", "현대차"] },
  { canonical: "네이버", aliases: ["네이버"] },
  { canonical: "카카오", aliases: ["카카오"] },
  { canonical: "쿠팡", aliases: ["쿠팡"] },
  { canonical: "배달의민족", aliases: ["배달의민족", "배민"] },
  { canonical: "토스", aliases: ["토스"] },
  { canonical: "삼성생명", aliases: ["삼성생명"] },
  { canonical: "삼성화재", aliases: ["삼성화재"] },
  { canonical: "국민은행", aliases: ["국민은행", "KB국민은행"] },
  { canonical: "신한은행", aliases: ["신한은행"] },
  { canonical: "우리은행", aliases: ["우리은행"] },
  { canonical: "하나은행", aliases: ["하나은행", "KEB하나은행"] },
  { canonical: "농협은행", aliases: ["농협은행", "NH농협은행"] },
  { canonical: "기업은행", aliases: ["기업은행", "IBK기업은행"] },
  { canonical: "대한항공", aliases: ["대한항공"] },
  { canonical: "아시아나항공", aliases: ["아시아나항공", "아시아나"] },
];

export const SCHOOL_LOOKUP_ENTRIES: LookupEntry[] = [
  { canonical: "가락초등학교", aliases: ["가락초등학교", "가락초"] },
  { canonical: "우면중학교", aliases: ["우면중학교", "우면중"] },
  { canonical: "삼성고등학교", aliases: ["삼성고등학교", "삼성고"] },
  { canonical: "가락중학교", aliases: ["가락중학교", "가락중"] },
  { canonical: "가락고등학교", aliases: ["가락고등학교", "가락고"] },
  { canonical: "우면초등학교", aliases: ["우면초등학교", "우면초"] },
  { canonical: "우면고등학교", aliases: ["우면고등학교", "우면고"] },
  { canonical: "서울대학교", aliases: ["서울대학교", "서울대"] },
  { canonical: "연세대학교", aliases: ["연세대학교", "연세대"] },
  { canonical: "고려대학교", aliases: ["고려대학교", "고려대"] },
  { canonical: "성균관대학교", aliases: ["성균관대학교", "성균관대"] },
  { canonical: "한양대학교", aliases: ["한양대학교", "한양대"] },
  { canonical: "중앙대학교", aliases: ["중앙대학교", "중앙대"] },
  { canonical: "경희대학교", aliases: ["경희대학교", "경희대"] },
  { canonical: "이화여자대학교", aliases: ["이화여자대학교", "이화여대"] },
  { canonical: "서강대학교", aliases: ["서강대학교", "서강대"] },
  { canonical: "건국대학교", aliases: ["건국대학교", "건국대"] },
];
