import type { SupportedLanguage } from "@/lib/language";

export type AdminChannelCatalog={title:string;searchPlaceholder:string;allStatus:string;active:string;inactive:string;reset:string;search:string;create:string;more:string;upload:string;download:string;total:string;perPage:string;login:string;order:string;channelId:string;channel:string;renderer:string;status:string;creator:string;updatedBy:string;updatedAt:string;manage:string;connectionTest:string;edit:string;loading:string;empty:string};

export const ADMIN_CHANNEL_CATALOGS={
ko:{title:"채널 관리",searchPlaceholder:"채널 아이디 또는 채널 이름을 검색하세요.",allStatus:"전체 사용여부",active:"사용",inactive:"미사용",reset:"초기화",search:"조회",create:"채널 생성",more:"채널 더보기",upload:"파일 업로드",download:"파일 다운로드",total:"전체",perPage:"개씩 보기",login:"로그인으로 이동",order:"순서",channelId:"채널 아이디",channel:"채널",renderer:"렌더러 타입",status:"사용여부",creator:"생성자",updatedBy:"최종수정자",updatedAt:"최종수정일시",manage:"관리",connectionTest:"연결 테스트",edit:"수정",loading:"불러오는 중입니다...",empty:"조회 결과가 없습니다."},
en:{title:"Channel Management",searchPlaceholder:"Search by channel ID or name.",allStatus:"All statuses",active:"Active",inactive:"Inactive",reset:"Reset",search:"Search",create:"Create channel",more:"More channel actions",upload:"Upload file",download:"Download file",total:"Total",perPage:"per page",login:"Go to login",order:"Order",channelId:"Channel ID",channel:"Channel",renderer:"Renderer type",status:"Status",creator:"Created by",updatedBy:"Updated by",updatedAt:"Last updated",manage:"Manage",connectionTest:"Connection test",edit:"Edit",loading:"Loading...",empty:"No results found."},
"zh-CN":{title:"渠道管理",searchPlaceholder:"按渠道 ID 或名称搜索。",allStatus:"全部状态",active:"使用",inactive:"未使用",reset:"重置",search:"查询",create:"创建渠道",more:"更多渠道操作",upload:"上传文件",download:"下载文件",total:"全部",perPage:"条/页",login:"前往登录",order:"顺序",channelId:"渠道 ID",channel:"渠道",renderer:"渲染器类型",status:"使用状态",creator:"创建者",updatedBy:"最后修改者",updatedAt:"最后修改时间",manage:"管理",connectionTest:"连接测试",edit:"修改",loading:"正在加载...",empty:"没有查询结果。"},
ja:{title:"チャネル管理",searchPlaceholder:"チャネル ID または名前を検索してください。",allStatus:"すべての使用状態",active:"使用",inactive:"未使用",reset:"初期化",search:"照会",create:"チャネル作成",more:"チャネルのその他操作",upload:"ファイルをアップロード",download:"ファイルをダウンロード",total:"全件",perPage:"件表示",login:"ログインへ移動",order:"順序",channelId:"チャネル ID",channel:"チャネル",renderer:"レンダラータイプ",status:"使用状態",creator:"作成者",updatedBy:"最終更新者",updatedAt:"最終更新日時",manage:"管理",connectionTest:"接続テスト",edit:"修正",loading:"読み込み中です...",empty:"照会結果がありません。"},
vi:{title:"Quản lý kênh",searchPlaceholder:"Tìm theo ID hoặc tên kênh.",allStatus:"Tất cả trạng thái",active:"Đang dùng",inactive:"Không dùng",reset:"Đặt lại",search:"Tra cứu",create:"Tạo kênh",more:"Thao tác kênh khác",upload:"Tải tệp lên",download:"Tải tệp xuống",total:"Tổng",perPage:"mục/trang",login:"Đến trang đăng nhập",order:"Thứ tự",channelId:"ID kênh",channel:"Kênh",renderer:"Loại trình kết xuất",status:"Trạng thái",creator:"Người tạo",updatedBy:"Người cập nhật",updatedAt:"Cập nhật lần cuối",manage:"Quản lý",connectionTest:"Kiểm tra kết nối",edit:"Sửa",loading:"Đang tải...",empty:"Không có kết quả."},
fr:{title:"Gestion des canaux",searchPlaceholder:"Rechercher par ID ou nom de canal.",allStatus:"Tous les statuts",active:"Actif",inactive:"Inactif",reset:"Réinitialiser",search:"Rechercher",create:"Créer un canal",more:"Autres actions",upload:"Importer un fichier",download:"Télécharger le fichier",total:"Total",perPage:"par page",login:"Aller à la connexion",order:"Ordre",channelId:"ID du canal",channel:"Canal",renderer:"Type de rendu",status:"Statut",creator:"Créé par",updatedBy:"Modifié par",updatedAt:"Dernière modification",manage:"Gérer",connectionTest:"Tester la connexion",edit:"Modifier",loading:"Chargement...",empty:"Aucun résultat."},
de:{title:"Kanalverwaltung",searchPlaceholder:"Nach Kanal-ID oder Namen suchen.",allStatus:"Alle Status",active:"Aktiv",inactive:"Inaktiv",reset:"Zurücksetzen",search:"Suchen",create:"Kanal erstellen",more:"Weitere Kanalaktionen",upload:"Datei hochladen",download:"Datei herunterladen",total:"Gesamt",perPage:"pro Seite",login:"Zur Anmeldung",order:"Reihenfolge",channelId:"Kanal-ID",channel:"Kanal",renderer:"Renderer-Typ",status:"Status",creator:"Erstellt von",updatedBy:"Geändert von",updatedAt:"Zuletzt geändert",manage:"Verwalten",connectionTest:"Verbindung testen",edit:"Bearbeiten",loading:"Wird geladen...",empty:"Keine Ergebnisse."},
} satisfies Record<SupportedLanguage,AdminChannelCatalog>;
