import type { SupportedLanguage } from "@/lib/language";

export type AdminBotstationStatusCatalog = { labels: Record<string, string> };

const enLabels: Record<string, string> = {
  "봇스테이션 연계 현황":"Bot Station integration status","검색 조건":"Search filters","봇 이름":"Bot name","최종 수정자":"Modified by","전체":"All","상태":"Status","봇스테이션 더보기":"More Bot Station actions","조회 중":"Loading","그룹":"Group","채널":"Channel","운영버전":"Live version","활성 채널":"Active channels","메시지":"Message","최종수정일시":"Last modified","최종수정자":"Modified by","봇스테이션 상세정보":"Bot Station details","닫기":"Close","취소":"Cancel","확인":"Confirm","메신저 연결 상세정보":"Messenger connection details","메신저":"Messenger","운영 점검 정보":"Operations check","인증 헤더":"Authentication header","지원 출력":"Supported output","로그 이벤트":"Log events","최근 상태 요약":"Recent status summary","현재 상태":"Current status","최근 응답/거부/실패":"Recent responses/rejections/failures","마지막 성공":"Last success","마지막 실패":"Last failure","최근 실패 사유":"Recent failure reason","최근 거부 상태코드":"Recent rejection status code","최근 fallback 이유":"Recent fallback reasons","최근 카카오 로그":"Recent Kakao logs","Kakao 입력/테스트 안내":"Kakao input/test guide","사용":"Use","설명":"Description","App ID 설명":"About App ID","App Secret 설명":"About App Secret","Callback URL 설명":"About Callback URL","로그인 정보가 없습니다.":"No sign-in information.","봇스테이션 연계 현황을 불러오지 못했습니다.":"Could not load Bot Station status.","봇스테이션 설정 저장 중 오류가 발생했습니다.":"An error occurred while saving Bot Station settings.","운영버전이 지정된 봇만 봇스테이션을 사용할 수 있습니다.":"Bot Station is available only for bots with a live version.","운영버전이 지정된 봇만 채널 연결을 저장할 수 있습니다.":"Channel connections can be saved only for bots with a live version.","봇스테이션 상세정보가 저장되었습니다.":"Bot Station details were saved.","메신저 연결 상세정보가 저장되었습니다.":"Messenger connection details were saved.","최근 실패 있음":"Recent failure","최근 응답 정상":"Recent response healthy","최근 이력 확인 필요":"Review recent history","운영버전 없음":"No live version","학습 필요":"Training required","운영":"Live","봇스테이션 미사용":"Bot Station disabled","활성 채널 없음":"No active channels","정상":"Healthy"
};

const makeCatalog = (overrides: Record<string, string>): AdminBotstationStatusCatalog => ({ labels: { ...enLabels, ...overrides } });
const koLabels = Object.fromEntries(Object.keys(enLabels).map((key) => [key, key]));

export const ADMIN_BOTSTATION_STATUS_CATALOGS = {
  ko: makeCatalog(koLabels),
  en: makeCatalog({}),
  "zh-CN": makeCatalog({ "봇스테이션 연계 현황":"Bot Station 集成状态","검색 조건":"搜索条件","봇 이름":"机器人名称","최종 수정자":"最后修改人","전체":"全部","상태":"状态","봇스테이션 더보기":"更多 Bot Station 操作","조회 중":"加载中","그룹":"组","채널":"渠道","운영버전":"运行版本","활성 채널":"活动渠道","메시지":"消息","최종수정일시":"最后修改时间","최종수정자":"最后修改人","봇스테이션 상세정보":"Bot Station 详细信息","닫기":"关闭","취소":"取消","확인":"确认","메신저 연결 상세정보":"消息工具连接详情","메신저":"消息工具","운영 점검 정보":"运行检查信息","인증 헤더":"认证标头","지원 출력":"支持的输出","로그 이벤트":"日志事件","최근 상태 요약":"最近状态摘要","현재 상태":"当前状态","최근 응답/거부/실패":"最近响应/拒绝/失败","마지막 성공":"最后成功","마지막 실패":"最后失败","최근 실패 사유":"最近失败原因","최근 거부 상태코드":"最近拒绝状态码","최근 fallback 이유":"最近 fallback 原因","최근 카카오 로그":"最近 Kakao 日志","Kakao 입력/테스트 안내":"Kakao 输入/测试指南","사용":"使用","설명":"说明" }),
  ja: makeCatalog({ "봇스테이션 연계 현황":"Bot Station連携状況","검색 조건":"検索条件","봇 이름":"ボット名","최종 수정자":"最終更新者","전체":"すべて","상태":"状態","봇스테이션 더보기":"Bot Stationのその他の操作","조회 중":"読み込み中","그룹":"グループ","채널":"チャネル","운영버전":"運用バージョン","활성 채널":"有効なチャネル","메시지":"メッセージ","최종수정일시":"最終更新日時","최종수정자":"最終更新者","봇스테이션 상세정보":"Bot Station詳細","닫기":"閉じる","취소":"キャンセル","확인":"確認","메신저 연결 상세정보":"メッセンジャー接続詳細","메신저":"メッセンジャー","운영 점검 정보":"運用点検情報","인증 헤더":"認証ヘッダー","지원 출력":"対応出力","로그 이벤트":"ログイベント","최근 상태 요약":"最近の状態概要","현재 상태":"現在の状態","최근 응답/거부/실패":"最近の応答/拒否/失敗","마지막 성공":"最終成功","마지막 실패":"最終失敗","최근 실패 사유":"最近の失敗理由","최근 거부 상태코드":"最近の拒否ステータスコード","최근 fallback 이유":"最近のfallback理由","최근 카카오 로그":"最近のKakaoログ","Kakao 입력/테스트 안내":"Kakao入力/テストガイド","사용":"使用","설명":"説明" }),
  vi: makeCatalog({ "봇스테이션 연계 현황":"Trạng thái tích hợp Bot Station","검색 조건":"Bộ lọc tìm kiếm","봇 이름":"Tên bot","최종 수정자":"Người sửa cuối","전체":"Tất cả","상태":"Trạng thái","봇스테이션 더보기":"Thêm thao tác Bot Station","조회 중":"Đang tải","그룹":"Nhóm","채널":"Kênh","운영버전":"Phiên bản vận hành","활성 채널":"Kênh hoạt động","메시지":"Tin nhắn","최종수정일시":"Sửa lần cuối","최종수정자":"Người sửa","봇스테이션 상세정보":"Chi tiết Bot Station","닫기":"Đóng","취소":"Hủy","확인":"Xác nhận","메신저 연결 상세정보":"Chi tiết kết nối messenger","메신저":"Messenger","운영 점검 정보":"Thông tin kiểm tra vận hành","인증 헤더":"Header xác thực","지원 출력":"Đầu ra hỗ trợ","로그 이벤트":"Sự kiện log","최근 상태 요약":"Tóm tắt trạng thái gần đây","현재 상태":"Trạng thái hiện tại","최근 응답/거부/실패":"Phản hồi/từ chối/lỗi gần đây","마지막 성공":"Thành công cuối","마지막 실패":"Lỗi cuối","최근 실패 사유":"Lý do lỗi gần đây","최근 거부 상태코드":"Mã trạng thái từ chối gần đây","최근 fallback 이유":"Lý do fallback gần đây","최근 카카오 로그":"Log Kakao gần đây","Kakao 입력/테스트 안내":"Hướng dẫn nhập/kiểm thử Kakao","사용":"Dùng","설명":"Mô tả" }),
  fr: makeCatalog({ "봇스테이션 연계 현황":"État d’intégration Bot Station","검색 조건":"Filtres de recherche","봇 이름":"Nom du bot","최종 수정자":"Modifié par","전체":"Tous","상태":"État","봇스테이션 더보기":"Autres actions Bot Station","조회 중":"Chargement","그룹":"Groupe","채널":"Canal","운영버전":"Version active","활성 채널":"Canaux actifs","메시지":"Message","최종수정일시":"Dernière modification","최종수정자":"Modifié par","봇스테이션 상세정보":"Détails de Bot Station","닫기":"Fermer","취소":"Annuler","확인":"Confirmer","메신저 연결 상세정보":"Détails de connexion de messagerie","메신저":"Messagerie","운영 점검 정보":"Contrôle d’exploitation","인증 헤더":"En-tête d’authentification","지원 출력":"Sortie prise en charge","로그 이벤트":"Événements du journal","최근 상태 요약":"Résumé de l’état récent","현재 상태":"État actuel","최근 응답/거부/실패":"Réponses/rejets/échecs récents","마지막 성공":"Dernier succès","마지막 실패":"Dernier échec","최근 실패 사유":"Motif du dernier échec","최근 거부 상태코드":"Code du dernier rejet","최근 fallback 이유":"Motifs de fallback récents","최근 카카오 로그":"Journaux Kakao récents","Kakao 입력/테스트 안내":"Guide de saisie/test Kakao","사용":"Utiliser","설명":"Description" }),
  de: makeCatalog({ "봇스테이션 연계 현황":"Bot-Station-Integrationsstatus","검색 조건":"Suchfilter","봇 이름":"Bot-Name","최종 수정자":"Geändert von","전체":"Alle","상태":"Status","봇스테이션 더보기":"Weitere Bot-Station-Aktionen","조회 중":"Wird geladen","그룹":"Gruppe","채널":"Kanal","운영버전":"Live-Version","활성 채널":"Aktive Kanäle","메시지":"Nachricht","최종수정일시":"Zuletzt geändert","최종수정자":"Geändert von","봇스테이션 상세정보":"Bot-Station-Details","닫기":"Schließen","취소":"Abbrechen","확인":"Bestätigen","메신저 연결 상세정보":"Messenger-Verbindungsdetails","메신저":"Messenger","운영 점검 정보":"Betriebsprüfung","인증 헤더":"Authentifizierungsheader","지원 출력":"Unterstützte Ausgabe","로그 이벤트":"Protokollereignisse","최근 상태 요약":"Letzte Statusübersicht","현재 상태":"Aktueller Status","최근 응답/거부/실패":"Letzte Antworten/Ablehnungen/Fehler","마지막 성공":"Letzter Erfolg","마지막 실패":"Letzter Fehler","최근 실패 사유":"Letzter Fehlergrund","최근 거부 상태코드":"Letzter Ablehnungsstatuscode","최근 fallback 이유":"Letzte Fallback-Gründe","최근 카카오 로그":"Letzte Kakao-Protokolle","Kakao 입력/테스트 안내":"Kakao-Eingabe-/Testanleitung","사용":"Verwenden","설명":"Beschreibung" }),
} satisfies Record<SupportedLanguage, AdminBotstationStatusCatalog>;

export function getAdminBotstationStatusLabel(copy: AdminBotstationStatusCatalog, value: string): string {
  return copy.labels[value] ?? value;
}