import type { SupportedLanguage } from "@/lib/language";

export type AdminUsersCatalog = {
  title:string; searchPlaceholder:string; allGroups:string; allRoles:string; allAccountStatuses:string; allSignupStatuses:string;
  roleNames:Record<string,string>; accountStatuses:Record<string,string>; signupStatuses:Record<string,string>;
  search:string; total:string; perPage:string; selected:string; goToLogin:string; selectUser:string; selectAll:string;
  columns:string[]; loading:string; empty:string; loginRequired:string; loadFailed:string;
};

export const ADMIN_USERS_CATALOGS = {
  ko:{title:"사용자 관리",searchPlaceholder:"사용자 계정 또는 사용자 이름을 검색하세요.",allGroups:"전체 그룹",allRoles:"전체 역할",allAccountStatuses:"전체 계정상태",allSignupStatuses:"전체 가입상태",roleNames:{curator:"큐레이터",operation_manager:"운영관리자",system_manager:"시스템관리자",it_admin:"IT관리자"},accountStatuses:{active:"활성",locked:"잠김",password_reset:"비밀번호 초기화",inactive:"비활성"},signupStatuses:{approved:"계정 승인",pending:"승인 요청",rejected:"승인 반려"},search:"조회",total:"전체 {count}건",perPage:"{count}개씩 보기",selected:"{count}개 선택",goToLogin:"로그인으로 이동",selectUser:"{loginId} 선택",selectAll:"전체 선택",columns:["","사용자 계정","사용자 이름","그룹","역할","신청일시","가입상태","계정상태"],loading:"불러오는 중입니다...",empty:"조회 결과가 없습니다.",loginRequired:"로그인이 필요합니다.",loadFailed:"사용자 목록을 불러오지 못했습니다."},
  en:{title:"User Management",searchPlaceholder:"Search by user account or name.",allGroups:"All groups",allRoles:"All roles",allAccountStatuses:"All account statuses",allSignupStatuses:"All signup statuses",roleNames:{curator:"Curator",operation_manager:"Operations Manager",system_manager:"System Manager",it_admin:"IT Administrator"},accountStatuses:{active:"Active",locked:"Locked",password_reset:"Password reset",inactive:"Inactive"},signupStatuses:{approved:"Approved",pending:"Pending approval",rejected:"Rejected"},search:"Search",total:"Total {count}",perPage:"{count} per page",selected:"{count} selected",goToLogin:"Go to login",selectUser:"Select {loginId}",selectAll:"Select all",columns:["","User Account","User Name","Group","Role","Requested At","Signup Status","Account Status"],loading:"Loading...",empty:"No results found.",loginRequired:"Login is required.",loadFailed:"Could not load the user list."},
  "zh-CN":{title:"用户管理",searchPlaceholder:"按用户账户或用户名搜索。",allGroups:"全部组",allRoles:"全部角色",allAccountStatuses:"全部账户状态",allSignupStatuses:"全部注册状态",roleNames:{curator:"策划员",operation_manager:"运营管理员",system_manager:"系统管理员",it_admin:"IT管理员"},accountStatuses:{active:"启用",locked:"已锁定",password_reset:"密码重置",inactive:"停用"},signupStatuses:{approved:"已批准",pending:"待批准",rejected:"已拒绝"},search:"查询",total:"共{count}项",perPage:"每页{count}项",selected:"已选择{count}项",goToLogin:"前往登录",selectUser:"选择{loginId}",selectAll:"全选",columns:["","用户账户","用户名","组","角色","申请时间","注册状态","账户状态"],loading:"加载中...",empty:"没有查询结果。",loginRequired:"需要登录。",loadFailed:"无法加载用户列表。"},
  ja:{title:"ユーザー管理",searchPlaceholder:"ユーザーアカウントまたは名前で検索します。",allGroups:"全グループ",allRoles:"全ロール",allAccountStatuses:"全アカウント状態",allSignupStatuses:"全登録状態",roleNames:{curator:"キュレーター",operation_manager:"運用管理者",system_manager:"システム管理者",it_admin:"IT管理者"},accountStatuses:{active:"有効",locked:"ロック",password_reset:"パスワード初期化",inactive:"無効"},signupStatuses:{approved:"承認済み",pending:"承認待ち",rejected:"却下"},search:"照会",total:"全{count}件",perPage:"{count}件表示",selected:"{count}件選択",goToLogin:"ログインへ",selectUser:"{loginId}を選択",selectAll:"すべて選択",columns:["","ユーザーアカウント","ユーザー名","グループ","ロール","申請日時","登録状態","アカウント状態"],loading:"読み込み中...",empty:"照会結果がありません。",loginRequired:"ログインが必要です。",loadFailed:"ユーザー一覧を取得できませんでした。"},
  vi:{title:"Quản lý người dùng",searchPlaceholder:"Tìm theo tài khoản hoặc tên người dùng.",allGroups:"Tất cả nhóm",allRoles:"Tất cả vai trò",allAccountStatuses:"Tất cả trạng thái tài khoản",allSignupStatuses:"Tất cả trạng thái đăng ký",roleNames:{curator:"Biên tập viên",operation_manager:"Quản lý vận hành",system_manager:"Quản trị hệ thống",it_admin:"Quản trị IT"},accountStatuses:{active:"Hoạt động",locked:"Bị khóa",password_reset:"Đặt lại mật khẩu",inactive:"Không hoạt động"},signupStatuses:{approved:"Đã duyệt",pending:"Chờ duyệt",rejected:"Từ chối"},search:"Tra cứu",total:"Tổng {count}",perPage:"{count} mỗi trang",selected:"Đã chọn {count}",goToLogin:"Đến đăng nhập",selectUser:"Chọn {loginId}",selectAll:"Chọn tất cả",columns:["","Tài khoản","Tên người dùng","Nhóm","Vai trò","Thời gian yêu cầu","Trạng thái đăng ký","Trạng thái tài khoản"],loading:"Đang tải...",empty:"Không có kết quả.",loginRequired:"Cần đăng nhập.",loadFailed:"Không thể tải danh sách người dùng."},
  fr:{title:"Gestion des utilisateurs",searchPlaceholder:"Rechercher par compte ou nom d’utilisateur.",allGroups:"Tous les groupes",allRoles:"Tous les rôles",allAccountStatuses:"Tous les états de compte",allSignupStatuses:"Tous les états d’inscription",roleNames:{curator:"Curateur",operation_manager:"Responsable d’exploitation",system_manager:"Administrateur système",it_admin:"Administrateur IT"},accountStatuses:{active:"Actif",locked:"Verrouillé",password_reset:"Réinitialisation du mot de passe",inactive:"Inactif"},signupStatuses:{approved:"Approuvé",pending:"En attente",rejected:"Refusé"},search:"Rechercher",total:"Total {count}",perPage:"{count} par page",selected:"{count} sélectionnés",goToLogin:"Aller à la connexion",selectUser:"Sélectionner {loginId}",selectAll:"Tout sélectionner",columns:["","Compte utilisateur","Nom d’utilisateur","Groupe","Rôle","Demandé le","État d’inscription","État du compte"],loading:"Chargement...",empty:"Aucun résultat.",loginRequired:"Connexion requise.",loadFailed:"Impossible de charger la liste des utilisateurs."},
  de:{title:"Benutzerverwaltung",searchPlaceholder:"Nach Benutzerkonto oder Name suchen.",allGroups:"Alle Gruppen",allRoles:"Alle Rollen",allAccountStatuses:"Alle Kontostatus",allSignupStatuses:"Alle Registrierungsstatus",roleNames:{curator:"Kurator",operation_manager:"Betriebsmanager",system_manager:"Systemadministrator",it_admin:"IT-Administrator"},accountStatuses:{active:"Aktiv",locked:"Gesperrt",password_reset:"Passwort zurücksetzen",inactive:"Inaktiv"},signupStatuses:{approved:"Genehmigt",pending:"Genehmigung ausstehend",rejected:"Abgelehnt"},search:"Suchen",total:"Gesamt {count}",perPage:"{count} pro Seite",selected:"{count} ausgewählt",goToLogin:"Zur Anmeldung",selectUser:"{loginId} auswählen",selectAll:"Alle auswählen",columns:["","Benutzerkonto","Benutzername","Gruppe","Rolle","Beantragt am","Registrierungsstatus","Kontostatus"],loading:"Wird geladen...",empty:"Keine Ergebnisse.",loginRequired:"Anmeldung erforderlich.",loadFailed:"Benutzerliste konnte nicht geladen werden."},
} satisfies Record<SupportedLanguage, AdminUsersCatalog>;

export function formatAdminUsersText(template:string, values:Record<string,string|number>) {
  return template.replace(/\{(\w+)\}/g, (_, key:string) => String(values[key] ?? ""));
}
