import type { SupportedLanguage } from "@/lib/language";

export type CommonVariableCatalog = {
  title: string; searchPlaceholder: string; allKinds: string; user: string; system: string; reset: string;
  search: string; add: string; more: string; upload: string; download: string; total: string; perPage: string;
  selected: string; delete: string; login: string; selectAll: string; category: string; name: string; value: string;
  description: string; updatedAt: string; updatedBy: string; loading: string; empty: string; select: string;
  unavailable: string; detail: string; close: string; readOnly: string; variableDescription: string; cancel: string;
  confirm: string; loginRequired: string; loadFailed: string; saved: string; added: string; saveFailed: string;
  deleted: string; deleteFailed: string; noUpload: string; uploadFailed: string; uploadResult: string;
};

export const COMMON_VARIABLE_CATALOGS = {
  ko: {
    title:"공통 변수 관리",searchPlaceholder:"변수명 또는 변수값을 검색하세요.",allKinds:"전체 구분",user:"사용자",system:"시스템",reset:"초기화",search:"조회",add:"공통 변수 추가",more:"공통 변수 더보기",upload:"파일 업로드",download:"파일 다운로드",total:"전체",perPage:"개씩 보기",selected:"개 선택",delete:"삭제",login:"로그인으로 이동",selectAll:"전체 선택",category:"구분",name:"변수명",value:"변수값",description:"설명",updatedAt:"최종수정일시",updatedBy:"최종수정자",loading:"불러오는 중입니다...",empty:"조회 결과가 없습니다.",select:"선택",unavailable:"선택 불가",detail:"공통 변수 상세 정보",close:"닫기",readOnly:"시스템 변수는 읽기 전용입니다.",variableDescription:"변수 설명",cancel:"취소",confirm:"확인",loginRequired:"로그인이 필요합니다.",loadFailed:"공통 변수를 불러오지 못했습니다.",saved:"공통 변수가 수정되었습니다.",added:"공통 변수가 추가되었습니다.",saveFailed:"공통 변수 저장에 실패했습니다.",deleted:"선택한 공통 변수가 삭제되었습니다.",deleteFailed:"공통 변수 삭제에 실패했습니다.",noUpload:"업로드 가능한 공통 변수가 없습니다.",uploadFailed:"공통 변수 업로드에 실패했습니다.",uploadResult:"{saved}건 업로드, {skipped}건 제외되었습니다.",
  },
  en: {
    title:"Common Variables",searchPlaceholder:"Search by variable name or value.",allKinds:"All types",user:"User",system:"System",reset:"Reset",search:"Search",add:"Add common variable",more:"More common-variable actions",upload:"Upload file",download:"Download file",total:"Total",perPage:"per page",selected:"selected",delete:"Delete",login:"Go to login",selectAll:"Select all",category:"Type",name:"Variable name",value:"Variable value",description:"Description",updatedAt:"Last updated",updatedBy:"Updated by",loading:"Loading...",empty:"No results found.",select:"Select",unavailable:"Unavailable",detail:"Common Variable Details",close:"Close",readOnly:"System variables are read-only.",variableDescription:"Variable description",cancel:"Cancel",confirm:"Confirm",loginRequired:"Login is required.",loadFailed:"Failed to load common variables.",saved:"The common variable was updated.",added:"The common variable was added.",saveFailed:"Failed to save the common variable.",deleted:"The selected common variables were deleted.",deleteFailed:"Failed to delete common variables.",noUpload:"No common variables can be uploaded.",uploadFailed:"Failed to upload common variables.",uploadResult:"{saved} uploaded, {skipped} skipped.",
  },
  "zh-CN": {
    title:"公共变量管理",searchPlaceholder:"按变量名或变量值搜索。",allKinds:"全部类型",user:"用户",system:"系统",reset:"重置",search:"查询",add:"添加公共变量",more:"更多公共变量操作",upload:"上传文件",download:"下载文件",total:"全部",perPage:"条/页",selected:"项已选",delete:"删除",login:"前往登录",selectAll:"全选",category:"类型",name:"变量名",value:"变量值",description:"说明",updatedAt:"最后修改时间",updatedBy:"最后修改者",loading:"正在加载...",empty:"没有查询结果。",select:"选择",unavailable:"不可选择",detail:"公共变量详细信息",close:"关闭",readOnly:"系统变量为只读。",variableDescription:"变量说明",cancel:"取消",confirm:"确认",loginRequired:"需要登录。",loadFailed:"无法加载公共变量。",saved:"公共变量已修改。",added:"公共变量已添加。",saveFailed:"保存公共变量失败。",deleted:"已删除所选公共变量。",deleteFailed:"删除公共变量失败。",noUpload:"没有可上传的公共变量。",uploadFailed:"上传公共变量失败。",uploadResult:"已上传 {saved} 条，排除 {skipped} 条。",
  },
  ja: {
    title:"共通変数管理",searchPlaceholder:"変数名または変数値を検索してください。",allKinds:"すべての区分",user:"ユーザー",system:"システム",reset:"初期化",search:"照会",add:"共通変数を追加",more:"共通変数のその他操作",upload:"ファイルをアップロード",download:"ファイルをダウンロード",total:"全件",perPage:"件表示",selected:"件選択",delete:"削除",login:"ログインへ移動",selectAll:"すべて選択",category:"区分",name:"変数名",value:"変数値",description:"説明",updatedAt:"最終更新日時",updatedBy:"最終更新者",loading:"読み込み中です...",empty:"照会結果がありません。",select:"選択",unavailable:"選択不可",detail:"共通変数の詳細情報",close:"閉じる",readOnly:"システム変数は読み取り専用です。",variableDescription:"変数の説明",cancel:"キャンセル",confirm:"確認",loginRequired:"ログインが必要です。",loadFailed:"共通変数を読み込めませんでした。",saved:"共通変数を修正しました。",added:"共通変数を追加しました。",saveFailed:"共通変数の保存に失敗しました。",deleted:"選択した共通変数を削除しました。",deleteFailed:"共通変数の削除に失敗しました。",noUpload:"アップロード可能な共通変数がありません。",uploadFailed:"共通変数のアップロードに失敗しました。",uploadResult:"{saved}件アップロード、{skipped}件除外しました。",
  },
  vi: {
    title:"Quản lý biến dùng chung",searchPlaceholder:"Tìm theo tên hoặc giá trị biến.",allKinds:"Tất cả loại",user:"Người dùng",system:"Hệ thống",reset:"Đặt lại",search:"Tra cứu",add:"Thêm biến dùng chung",more:"Thao tác khác",upload:"Tải tệp lên",download:"Tải tệp xuống",total:"Tổng",perPage:"mục/trang",selected:"đã chọn",delete:"Xóa",login:"Đến trang đăng nhập",selectAll:"Chọn tất cả",category:"Loại",name:"Tên biến",value:"Giá trị biến",description:"Mô tả",updatedAt:"Cập nhật lần cuối",updatedBy:"Người cập nhật",loading:"Đang tải...",empty:"Không có kết quả.",select:"Chọn",unavailable:"Không thể chọn",detail:"Chi tiết biến dùng chung",close:"Đóng",readOnly:"Biến hệ thống chỉ được đọc.",variableDescription:"Mô tả biến",cancel:"Hủy",confirm:"Xác nhận",loginRequired:"Cần đăng nhập.",loadFailed:"Không thể tải biến dùng chung.",saved:"Đã cập nhật biến dùng chung.",added:"Đã thêm biến dùng chung.",saveFailed:"Không thể lưu biến dùng chung.",deleted:"Đã xóa các biến đã chọn.",deleteFailed:"Không thể xóa biến dùng chung.",noUpload:"Không có biến dùng chung để tải lên.",uploadFailed:"Không thể tải biến dùng chung lên.",uploadResult:"Đã tải lên {saved}, loại trừ {skipped}.",
  },
  fr: {
    title:"Gestion des variables communes",searchPlaceholder:"Rechercher par nom ou valeur de variable.",allKinds:"Tous les types",user:"Utilisateur",system:"Système",reset:"Réinitialiser",search:"Rechercher",add:"Ajouter une variable commune",more:"Autres actions",upload:"Importer un fichier",download:"Télécharger le fichier",total:"Total",perPage:"par page",selected:"sélectionné(s)",delete:"Supprimer",login:"Aller à la connexion",selectAll:"Tout sélectionner",category:"Type",name:"Nom de variable",value:"Valeur",description:"Description",updatedAt:"Dernière modification",updatedBy:"Modifié par",loading:"Chargement...",empty:"Aucun résultat.",select:"Sélectionner",unavailable:"Indisponible",detail:"Détails de la variable commune",close:"Fermer",readOnly:"Les variables système sont en lecture seule.",variableDescription:"Description de la variable",cancel:"Annuler",confirm:"Confirmer",loginRequired:"Connexion requise.",loadFailed:"Impossible de charger les variables communes.",saved:"La variable commune a été modifiée.",added:"La variable commune a été ajoutée.",saveFailed:"Impossible d’enregistrer la variable commune.",deleted:"Les variables sélectionnées ont été supprimées.",deleteFailed:"Impossible de supprimer les variables communes.",noUpload:"Aucune variable commune ne peut être importée.",uploadFailed:"Impossible d’importer les variables communes.",uploadResult:"{saved} importées, {skipped} ignorées.",
  },
  de: {
    title:"Gemeinsame Variablen",searchPlaceholder:"Nach Variablenname oder -wert suchen.",allKinds:"Alle Typen",user:"Benutzer",system:"System",reset:"Zurücksetzen",search:"Suchen",add:"Gemeinsame Variable hinzufügen",more:"Weitere Aktionen",upload:"Datei hochladen",download:"Datei herunterladen",total:"Gesamt",perPage:"pro Seite",selected:"ausgewählt",delete:"Löschen",login:"Zur Anmeldung",selectAll:"Alle auswählen",category:"Typ",name:"Variablenname",value:"Variablenwert",description:"Beschreibung",updatedAt:"Zuletzt geändert",updatedBy:"Geändert von",loading:"Wird geladen...",empty:"Keine Ergebnisse.",select:"Auswählen",unavailable:"Nicht auswählbar",detail:"Details der gemeinsamen Variable",close:"Schließen",readOnly:"Systemvariablen sind schreibgeschützt.",variableDescription:"Variablenbeschreibung",cancel:"Abbrechen",confirm:"Bestätigen",loginRequired:"Anmeldung erforderlich.",loadFailed:"Gemeinsame Variablen konnten nicht geladen werden.",saved:"Die gemeinsame Variable wurde aktualisiert.",added:"Die gemeinsame Variable wurde hinzugefügt.",saveFailed:"Die gemeinsame Variable konnte nicht gespeichert werden.",deleted:"Die ausgewählten Variablen wurden gelöscht.",deleteFailed:"Gemeinsame Variablen konnten nicht gelöscht werden.",noUpload:"Keine gemeinsamen Variablen zum Hochladen vorhanden.",uploadFailed:"Gemeinsame Variablen konnten nicht hochgeladen werden.",uploadResult:"{saved} hochgeladen, {skipped} übersprungen.",
  },
} satisfies Record<SupportedLanguage, CommonVariableCatalog>;

export function formatCommonVariableText(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}
