import type { SupportedLanguage } from "@/lib/language";

export type AdminConversationCatalog = {
  title: string; searchPlaceholder: string; pageSize: string; columns: string[]; detail: string; close: string;
  sessionDetail: string; sessionConversation: string; diagnosticSummary: string; channel: string; bot: string; user: string;
  sessionStart: string; result: string; userCount: string; messageCount: string; completionReason: string; dialogEnded: string;
  sessionEnded: string; runtime: string; recentProblem: string; problemLocation: string; roomId: string; externalRoom: string;
  yes: string; no: string; viewQueue: string; viewApi: string; conversationFlow: string; userUtterance: string;
  emptyMessages: string; variableTrace: string; variablePreview: string; emptyVariables: string; progressEvents: string;
  emptyEvents: string; storedData: string; intentModule: string; emptyUtterances: string; averageResponseTime: string;
};

export const ADMIN_CONVERSATION_CATALOGS = {
  ko: { title:"대화 이력 조회",searchPlaceholder:"사용자 또는 의도명을 검색하세요.",pageSize:"20개씩 보기",columns:["","그룹","채널","봇","버전","사용자 발화","의도/모듈명","발화일시","실행 결과","오류/진행"],detail:"상세",close:"닫기",sessionDetail:"세션 상세 이력",sessionConversation:"세션 대화 이력",diagnosticSummary:"진단 요약",channel:"채널",bot:"봇",user:"사용자",sessionStart:"세션 시작",result:"결과",userCount:"사용자 발화 수",messageCount:"전체 메시지 수",completionReason:"완료 사유",dialogEnded:"대화 종료",sessionEnded:"세션 종료",runtime:"오류/진행",recentProblem:"최근 문제 이벤트",problemLocation:"문제 위치",roomId:"대화방 ID",externalRoom:"외부 대화방",yes:"예",no:"아니오",viewQueue:"Queue 이력에서 보기",viewApi:"API 이력에서 보기",conversationFlow:"세션 대화 흐름",userUtterance:"사용자 발화",emptyMessages:"저장된 채널 대화 메시지가 없습니다.",variableTrace:"변수 변경 추적",variablePreview:"변수 값 미리보기",emptyVariables:"저장된 변수 변경 이벤트가 없습니다.",progressEvents:"진행 이벤트",emptyEvents:"저장된 런타임 이벤트가 없습니다.",storedData:"저장 데이터",intentModule:"의도/모듈명",emptyUtterances:"저장된 사용자 발화가 없습니다.",averageResponseTime:"평균 응답시간" },
  en: { title:"Conversation history",searchPlaceholder:"Search by user or intent name.",pageSize:"20 per page",columns:["","Group","Channel","Bot","Version","User utterance","Intent/Module","Uttered at","Result","Error/Progress"],detail:"Details",close:"Close",sessionDetail:"Session details",sessionConversation:"Session conversation",diagnosticSummary:"Diagnostic summary",channel:"Channel",bot:"Bot",user:"User",sessionStart:"Session started",result:"Result",userCount:"User utterances",messageCount:"Total messages",completionReason:"Completion reason",dialogEnded:"Conversation ended",sessionEnded:"Session ended",runtime:"Error/Progress",recentProblem:"Latest issue",problemLocation:"Issue location",roomId:"Room ID",externalRoom:"External room",yes:"Yes",no:"No",viewQueue:"View Queue history",viewApi:"View API history",conversationFlow:"Session conversation flow",userUtterance:"User utterance",emptyMessages:"No saved channel messages.",variableTrace:"Variable change trace",variablePreview:"Variable value preview",emptyVariables:"No saved variable change events.",progressEvents:"Progress events",emptyEvents:"No saved runtime events.",storedData:"Stored data",intentModule:"Intent/Module",emptyUtterances:"No saved user utterances.",averageResponseTime:"Average response time" },
  "zh-CN": { title:"对话记录查询",searchPlaceholder:"按用户或意图名称搜索。",pageSize:"每页20条",columns:["","组","渠道","机器人","版本","用户话语","意图/模块","发话时间","执行结果","错误/进度"],detail:"详情",close:"关闭",sessionDetail:"会话详情",sessionConversation:"会话对话记录",diagnosticSummary:"诊断摘要",channel:"渠道",bot:"机器人",user:"用户",sessionStart:"会话开始",result:"结果",userCount:"用户话语数",messageCount:"消息总数",completionReason:"完成原因",dialogEnded:"对话结束",sessionEnded:"会话结束",runtime:"错误/进度",recentProblem:"最近问题事件",problemLocation:"问题位置",roomId:"对话房间 ID",externalRoom:"外部房间",yes:"是",no:"否",viewQueue:"查看 Queue 记录",viewApi:"查看 API 记录",conversationFlow:"会话对话流程",userUtterance:"用户话语",emptyMessages:"没有保存的渠道对话消息。",variableTrace:"变量变更追踪",variablePreview:"变量值预览",emptyVariables:"没有保存的变量变更事件。",progressEvents:"进度事件",emptyEvents:"没有保存的运行时事件。",storedData:"存储数据",intentModule:"意图/模块",emptyUtterances:"没有保存的用户话语。",averageResponseTime:"平均响应时间" },
  ja: { title:"会話履歴照会",searchPlaceholder:"ユーザーまたはインテント名を検索してください。",pageSize:"20件表示",columns:["","グループ","チャネル","ボット","バージョン","ユーザー発話","インテント/モジュール","発話日時","実行結果","エラー/進行"],detail:"詳細",close:"閉じる",sessionDetail:"セッション詳細履歴",sessionConversation:"セッション会話履歴",diagnosticSummary:"診断概要",channel:"チャネル",bot:"ボット",user:"ユーザー",sessionStart:"セッション開始",result:"結果",userCount:"ユーザー発話数",messageCount:"全メッセージ数",completionReason:"完了理由",dialogEnded:"会話終了",sessionEnded:"セッション終了",runtime:"エラー/進行",recentProblem:"直近の問題イベント",problemLocation:"問題位置",roomId:"会話ルーム ID",externalRoom:"外部会話ルーム",yes:"はい",no:"いいえ",viewQueue:"Queue 履歴で表示",viewApi:"API 履歴で表示",conversationFlow:"セッション会話フロー",userUtterance:"ユーザー発話",emptyMessages:"保存されたチャネル会話メッセージがありません。",variableTrace:"変数変更追跡",variablePreview:"変数値プレビュー",emptyVariables:"保存された変数変更イベントがありません。",progressEvents:"進行イベント",emptyEvents:"保存されたランタイムイベントがありません。",storedData:"保存データ",intentModule:"インテント/モジュール",emptyUtterances:"保存されたユーザー発話がありません。",averageResponseTime:"平均応答時間" },
  vi: { title:"Lịch sử hội thoại",searchPlaceholder:"Tìm theo người dùng hoặc tên ý định.",pageSize:"20 mục/trang",columns:["","Nhóm","Kênh","Bot","Phiên bản","Phát ngôn người dùng","Ý định/Mô-đun","Thời gian","Kết quả","Lỗi/Tiến trình"],detail:"Chi tiết",close:"Đóng",sessionDetail:"Chi tiết phiên",sessionConversation:"Hội thoại phiên",diagnosticSummary:"Tóm tắt chẩn đoán",channel:"Kênh",bot:"Bot",user:"Người dùng",sessionStart:"Bắt đầu phiên",result:"Kết quả",userCount:"Số phát ngôn",messageCount:"Tổng tin nhắn",completionReason:"Lý do hoàn tất",dialogEnded:"Hội thoại kết thúc",sessionEnded:"Phiên kết thúc",runtime:"Lỗi/Tiến trình",recentProblem:"Sự cố gần nhất",problemLocation:"Vị trí sự cố",roomId:"ID phòng",externalRoom:"Phòng bên ngoài",yes:"Có",no:"Không",viewQueue:"Xem lịch sử Queue",viewApi:"Xem lịch sử API",conversationFlow:"Luồng hội thoại phiên",userUtterance:"Phát ngôn người dùng",emptyMessages:"Không có tin nhắn kênh đã lưu.",variableTrace:"Theo dõi thay đổi biến",variablePreview:"Xem trước giá trị biến",emptyVariables:"Không có sự kiện thay đổi biến.",progressEvents:"Sự kiện tiến trình",emptyEvents:"Không có sự kiện runtime.",storedData:"Dữ liệu đã lưu",intentModule:"Ý định/Mô-đun",emptyUtterances:"Không có phát ngôn người dùng.",averageResponseTime:"Thời gian phản hồi trung bình" },
  fr: { title:"Historique des conversations",searchPlaceholder:"Rechercher par utilisateur ou intention.",pageSize:"20 par page",columns:["","Groupe","Canal","Bot","Version","Énoncé utilisateur","Intention/Module","Date","Résultat","Erreur/Progression"],detail:"Détails",close:"Fermer",sessionDetail:"Détails de session",sessionConversation:"Conversation de session",diagnosticSummary:"Résumé du diagnostic",channel:"Canal",bot:"Bot",user:"Utilisateur",sessionStart:"Début de session",result:"Résultat",userCount:"Énoncés utilisateur",messageCount:"Total des messages",completionReason:"Motif de fin",dialogEnded:"Conversation terminée",sessionEnded:"Session terminée",runtime:"Erreur/Progression",recentProblem:"Dernier incident",problemLocation:"Emplacement du problème",roomId:"ID de salle",externalRoom:"Salle externe",yes:"Oui",no:"Non",viewQueue:"Voir l’historique Queue",viewApi:"Voir l’historique API",conversationFlow:"Flux de conversation",userUtterance:"Énoncé utilisateur",emptyMessages:"Aucun message de canal enregistré.",variableTrace:"Suivi des variables",variablePreview:"Aperçu des valeurs",emptyVariables:"Aucun événement de modification de variable.",progressEvents:"Événements de progression",emptyEvents:"Aucun événement d’exécution enregistré.",storedData:"Données enregistrées",intentModule:"Intention/Module",emptyUtterances:"Aucun énoncé utilisateur enregistré.",averageResponseTime:"Temps de réponse moyen" },
  de: { title:"Gesprächsverlauf",searchPlaceholder:"Nach Benutzer oder Intent suchen.",pageSize:"20 pro Seite",columns:["","Gruppe","Kanal","Bot","Version","Benutzeräußerung","Intent/Modul","Zeit","Ergebnis","Fehler/Fortschritt"],detail:"Details",close:"Schließen",sessionDetail:"Sitzungsdetails",sessionConversation:"Sitzungsgespräch",diagnosticSummary:"Diagnoseübersicht",channel:"Kanal",bot:"Bot",user:"Benutzer",sessionStart:"Sitzungsbeginn",result:"Ergebnis",userCount:"Benutzeräußerungen",messageCount:"Nachrichten gesamt",completionReason:"Abschlussgrund",dialogEnded:"Gespräch beendet",sessionEnded:"Sitzung beendet",runtime:"Fehler/Fortschritt",recentProblem:"Letztes Problem",problemLocation:"Problemstelle",roomId:"Raum-ID",externalRoom:"Externer Raum",yes:"Ja",no:"Nein",viewQueue:"Queue-Verlauf anzeigen",viewApi:"API-Verlauf anzeigen",conversationFlow:"Sitzungsgesprächsfluss",userUtterance:"Benutzeräußerung",emptyMessages:"Keine gespeicherten Kanalnachrichten.",variableTrace:"Variablenänderungen",variablePreview:"Variablenwert-Vorschau",emptyVariables:"Keine gespeicherten Variablenereignisse.",progressEvents:"Fortschrittsereignisse",emptyEvents:"Keine gespeicherten Laufzeitereignisse.",storedData:"Gespeicherte Daten",intentModule:"Intent/Modul",emptyUtterances:"Keine gespeicherten Benutzeräußerungen.",averageResponseTime:"Durchschnittliche Antwortzeit" },
} satisfies Record<SupportedLanguage,AdminConversationCatalog>;

export type AdminConversationRuntimeCatalog = {
  buttonSelection: string; input: string; selection: string; richFormResponse: string;
  richFormCard: string; runtimeError: string; normal: string; defaultBot: string;
};

export const ADMIN_CONVERSATION_RUNTIME_CATALOGS = {
  ko:{buttonSelection:"버튼 선택",input:"입력",selection:"선택",richFormResponse:"RichForm 응답",richFormCard:"RichForm 카드",runtimeError:"런타임 오류",normal:"정상",defaultBot:"Aidot 봇"},
  en:{buttonSelection:"Button selection",input:"Input",selection:"Selection",richFormResponse:"RichForm response",richFormCard:"RichForm card",runtimeError:"Runtime error",normal:"Normal",defaultBot:"Aidot bot"},
  "zh-CN":{buttonSelection:"按钮选择",input:"输入",selection:"选择",richFormResponse:"RichForm 响应",richFormCard:"RichForm 卡片",runtimeError:"运行时错误",normal:"正常",defaultBot:"Aidot 机器人"},
  ja:{buttonSelection:"ボタン選択",input:"入力",selection:"選択",richFormResponse:"RichForm 応答",richFormCard:"RichForm カード",runtimeError:"ランタイムエラー",normal:"正常",defaultBot:"Aidot ボット"},
  vi:{buttonSelection:"Chọn nút",input:"Nhập",selection:"Lựa chọn",richFormResponse:"Phản hồi RichForm",richFormCard:"Thẻ RichForm",runtimeError:"Lỗi runtime",normal:"Bình thường",defaultBot:"Bot Aidot"},
  fr:{buttonSelection:"Sélection du bouton",input:"Saisie",selection:"Sélection",richFormResponse:"Réponse RichForm",richFormCard:"Carte RichForm",runtimeError:"Erreur d’exécution",normal:"Normal",defaultBot:"Bot Aidot"},
  de:{buttonSelection:"Schaltflächenauswahl",input:"Eingabe",selection:"Auswahl",richFormResponse:"RichForm-Antwort",richFormCard:"RichForm-Karte",runtimeError:"Laufzeitfehler",normal:"Normal",defaultBot:"Aidot-Bot"},
} satisfies Record<SupportedLanguage,AdminConversationRuntimeCatalog>;
