import type { SupportedLanguage } from "@/lib/language";

export type AdminUsersCatalog = {
  title:string; searchPlaceholder:string; allGroups:string; allRoles:string; allAccountStatuses:string; allSignupStatuses:string;
  roleNames:Record<string,string>; accountStatuses:Record<string,string>; signupStatuses:Record<string,string>;
  search:string; total:string; perPage:string; selected:string; goToLogin:string; selectUser:string; selectAll:string;
  columns:string[]; loading:string; empty:string; loginRequired:string; loadFailed:string;
  detailForm:{title:string;subtitle:string;back:string;loading:string;invalidId:string;loadFailed:string;actionError:string;updated:string;deleted:string;approved:string;rejected:string;info:string;account:string;name:string;server:string;defaultServer:string;group:string;requestedAt:string;signupStatus:string;accountStatus:string;language:string;comment:string;approveTitle:string;editTitle:string;role:string;approve:string;reject:string;save:string;cannotDelete:string;delete:string;currentRole:string;groupHint:string};
};

export const ADMIN_USERS_CATALOGS = {
  ko:{title:"사용자 관리",searchPlaceholder:"사용자 계정 또는 사용자 이름을 검색하세요.",allGroups:"전체 그룹",allRoles:"전체 역할",allAccountStatuses:"전체 계정상태",allSignupStatuses:"전체 가입상태",roleNames:{curator:"큐레이터",operation_manager:"운영관리자",system_manager:"시스템관리자",it_admin:"IT관리자"},accountStatuses:{active:"활성",locked:"잠김",password_reset:"비밀번호 초기화",inactive:"비활성"},signupStatuses:{approved:"계정 승인",pending:"승인 요청",rejected:"승인 반려"},search:"조회",total:"전체 {count}건",perPage:"{count}개씩 보기",selected:"{count}개 선택",goToLogin:"로그인으로 이동",selectUser:"{loginId} 선택",selectAll:"전체 선택",columns:["","사용자 계정","사용자 이름","그룹","역할","신청일시","가입상태","계정상태"],loading:"불러오는 중입니다...",empty:"조회 결과가 없습니다.",loginRequired:"로그인이 필요합니다.",loadFailed:"사용자 목록을 불러오지 못했습니다.",detailForm:{title:"사용자 상세",subtitle:"사용자 관리 화면과 연결된 승인/상태 관리 페이지입니다.",back:"목록으로",loading:"불러오는 중입니다...",invalidId:"사용자 식별 정보가 올바르지 않습니다.",loadFailed:"상세 정보를 불러오지 못했습니다.",actionError:"작업 처리 중 오류가 발생했습니다.",updated:"사용자 정보가 변경되었습니다.",deleted:"사용자가 삭제되었습니다.",approved:"회원가입 신청이 승인되었습니다.",rejected:"회원가입 신청이 반려되었습니다.",info:"기본 정보",account:"사용자 계정",name:"사용자 이름",server:"서버",defaultServer:"기본 서버",group:"그룹",requestedAt:"신청일시",signupStatus:"가입상태",accountStatus:"계정상태",language:"언어",comment:"코멘트",approveTitle:"사용자 승인",editTitle:"사용자 정보 수정",role:"역할",approve:"승인",reject:"반려",save:"저장",cannotDelete:"삭제 불가",delete:"삭제",currentRole:"현재 선택 역할: {role}",groupHint:"현재 선택 그룹으로 변경되면 해당 그룹에 소속된 봇만 접근 가능합니다."}},
  en:{title:"User Management",searchPlaceholder:"Search by user account or name.",allGroups:"All groups",allRoles:"All roles",allAccountStatuses:"All account statuses",allSignupStatuses:"All signup statuses",roleNames:{curator:"Curator",operation_manager:"Operations Manager",system_manager:"System Manager",it_admin:"IT Administrator"},accountStatuses:{active:"Active",locked:"Locked",password_reset:"Password reset",inactive:"Inactive"},signupStatuses:{approved:"Approved",pending:"Pending approval",rejected:"Rejected"},search:"Search",total:"Total {count}",perPage:"{count} per page",selected:"{count} selected",goToLogin:"Go to login",selectUser:"Select {loginId}",selectAll:"Select all",columns:["","User Account","User Name","Group","Role","Requested At","Signup Status","Account Status"],loading:"Loading...",empty:"No results found.",loginRequired:"Login is required.",loadFailed:"Could not load the user list.",detailForm:{title:"User Details",subtitle:"Manage user approval and account status.",back:"Back to list",loading:"Loading...",invalidId:"The user identifier is invalid.",loadFailed:"Could not load the details.",actionError:"An error occurred while processing the action.",updated:"User information was updated.",deleted:"The user was deleted.",approved:"The signup request was approved.",rejected:"The signup request was rejected.",info:"Basic Information",account:"User Account",name:"User Name",server:"Server",defaultServer:"Default Server",group:"Group",requestedAt:"Requested At",signupStatus:"Signup Status",accountStatus:"Account Status",language:"Language",comment:"Comment",approveTitle:"Approve User",editTitle:"Edit User",role:"Role",approve:"Approve",reject:"Reject",save:"Save",cannotDelete:"Cannot delete",delete:"Delete",currentRole:"Selected role: {role}",groupHint:"After changing the group, the user can access only bots belonging to that group."}},
  "zh-CN":{title:"用户管理",searchPlaceholder:"按用户账户或用户名搜索。",allGroups:"全部组",allRoles:"全部角色",allAccountStatuses:"全部账户状态",allSignupStatuses:"全部注册状态",roleNames:{curator:"策划员",operation_manager:"运营管理员",system_manager:"系统管理员",it_admin:"IT管理员"},accountStatuses:{active:"启用",locked:"已锁定",password_reset:"密码重置",inactive:"停用"},signupStatuses:{approved:"已批准",pending:"待批准",rejected:"已拒绝"},search:"查询",total:"共{count}项",perPage:"每页{count}项",selected:"已选择{count}项",goToLogin:"前往登录",selectUser:"选择{loginId}",selectAll:"全选",columns:["","用户账户","用户名","组","角色","申请时间","注册状态","账户状态"],loading:"加载中...",empty:"没有查询结果。",loginRequired:"需要登录。",loadFailed:"无法加载用户列表。",detailForm:{title:"用户详情",subtitle:"管理用户批准和账户状态。",back:"返回列表",loading:"加载中...",invalidId:"用户标识信息无效。",loadFailed:"无法加载详细信息。",actionError:"处理操作时发生错误。",updated:"用户信息已更新。",deleted:"用户已删除。",approved:"注册申请已批准。",rejected:"注册申请已拒绝。",info:"基本信息",account:"用户账户",name:"用户名",server:"服务器",defaultServer:"默认服务器",group:"组",requestedAt:"申请时间",signupStatus:"注册状态",accountStatus:"账户状态",language:"语言",comment:"备注",approveTitle:"批准用户",editTitle:"修改用户",role:"角色",approve:"批准",reject:"拒绝",save:"保存",cannotDelete:"无法删除",delete:"删除",currentRole:"当前角色：{role}",groupHint:"更改组后，用户只能访问该组所属的机器人。"}},
  ja:{title:"ユーザー管理",searchPlaceholder:"ユーザーアカウントまたは名前で検索します。",allGroups:"全グループ",allRoles:"全ロール",allAccountStatuses:"全アカウント状態",allSignupStatuses:"全登録状態",roleNames:{curator:"キュレーター",operation_manager:"運用管理者",system_manager:"システム管理者",it_admin:"IT管理者"},accountStatuses:{active:"有効",locked:"ロック",password_reset:"パスワード初期化",inactive:"無効"},signupStatuses:{approved:"承認済み",pending:"承認待ち",rejected:"却下"},search:"照会",total:"全{count}件",perPage:"{count}件表示",selected:"{count}件選択",goToLogin:"ログインへ",selectUser:"{loginId}を選択",selectAll:"すべて選択",columns:["","ユーザーアカウント","ユーザー名","グループ","ロール","申請日時","登録状態","アカウント状態"],loading:"読み込み中...",empty:"照会結果がありません。",loginRequired:"ログインが必要です。",loadFailed:"ユーザー一覧を取得できませんでした。",detailForm:{title:"ユーザー詳細",subtitle:"ユーザー承認とアカウント状態を管理します。",back:"一覧へ",loading:"読み込み中...",invalidId:"ユーザー識別情報が正しくありません。",loadFailed:"詳細情報を取得できませんでした。",actionError:"処理中にエラーが発生しました。",updated:"ユーザー情報を更新しました。",deleted:"ユーザーを削除しました。",approved:"登録申請を承認しました。",rejected:"登録申請を却下しました。",info:"基本情報",account:"ユーザーアカウント",name:"ユーザー名",server:"サーバー",defaultServer:"基本サーバー",group:"グループ",requestedAt:"申請日時",signupStatus:"登録状態",accountStatus:"アカウント状態",language:"言語",comment:"コメント",approveTitle:"ユーザー承認",editTitle:"ユーザー情報修正",role:"ロール",approve:"承認",reject:"却下",save:"保存",cannotDelete:"削除不可",delete:"削除",currentRole:"現在のロール: {role}",groupHint:"グループ変更後は、そのグループに属するボットのみアクセスできます。"}},
  vi:{title:"Quản lý người dùng",searchPlaceholder:"Tìm theo tài khoản hoặc tên người dùng.",allGroups:"Tất cả nhóm",allRoles:"Tất cả vai trò",allAccountStatuses:"Tất cả trạng thái tài khoản",allSignupStatuses:"Tất cả trạng thái đăng ký",roleNames:{curator:"Biên tập viên",operation_manager:"Quản lý vận hành",system_manager:"Quản trị hệ thống",it_admin:"Quản trị IT"},accountStatuses:{active:"Hoạt động",locked:"Bị khóa",password_reset:"Đặt lại mật khẩu",inactive:"Không hoạt động"},signupStatuses:{approved:"Đã duyệt",pending:"Chờ duyệt",rejected:"Từ chối"},search:"Tra cứu",total:"Tổng {count}",perPage:"{count} mỗi trang",selected:"Đã chọn {count}",goToLogin:"Đến đăng nhập",selectUser:"Chọn {loginId}",selectAll:"Chọn tất cả",columns:["","Tài khoản","Tên người dùng","Nhóm","Vai trò","Thời gian yêu cầu","Trạng thái đăng ký","Trạng thái tài khoản"],loading:"Đang tải...",empty:"Không có kết quả.",loginRequired:"Cần đăng nhập.",loadFailed:"Không thể tải danh sách người dùng.",detailForm:{title:"Chi tiết người dùng",subtitle:"Quản lý phê duyệt và trạng thái tài khoản.",back:"Về danh sách",loading:"Đang tải...",invalidId:"Thông tin định danh người dùng không hợp lệ.",loadFailed:"Không thể tải thông tin chi tiết.",actionError:"Đã xảy ra lỗi khi xử lý.",updated:"Đã cập nhật thông tin người dùng.",deleted:"Đã xóa người dùng.",approved:"Đã duyệt yêu cầu đăng ký.",rejected:"Đã từ chối yêu cầu đăng ký.",info:"Thông tin cơ bản",account:"Tài khoản",name:"Tên người dùng",server:"Máy chủ",defaultServer:"Máy chủ mặc định",group:"Nhóm",requestedAt:"Thời gian yêu cầu",signupStatus:"Trạng thái đăng ký",accountStatus:"Trạng thái tài khoản",language:"Ngôn ngữ",comment:"Nhận xét",approveTitle:"Duyệt người dùng",editTitle:"Sửa người dùng",role:"Vai trò",approve:"Duyệt",reject:"Từ chối",save:"Lưu",cannotDelete:"Không thể xóa",delete:"Xóa",currentRole:"Vai trò đã chọn: {role}",groupHint:"Sau khi đổi nhóm, người dùng chỉ truy cập được các bot thuộc nhóm đó."}},
  fr:{title:"Gestion des utilisateurs",searchPlaceholder:"Rechercher par compte ou nom d’utilisateur.",allGroups:"Tous les groupes",allRoles:"Tous les rôles",allAccountStatuses:"Tous les états de compte",allSignupStatuses:"Tous les états d’inscription",roleNames:{curator:"Curateur",operation_manager:"Responsable d’exploitation",system_manager:"Administrateur système",it_admin:"Administrateur IT"},accountStatuses:{active:"Actif",locked:"Verrouillé",password_reset:"Réinitialisation du mot de passe",inactive:"Inactif"},signupStatuses:{approved:"Approuvé",pending:"En attente",rejected:"Refusé"},search:"Rechercher",total:"Total {count}",perPage:"{count} par page",selected:"{count} sélectionnés",goToLogin:"Aller à la connexion",selectUser:"Sélectionner {loginId}",selectAll:"Tout sélectionner",columns:["","Compte utilisateur","Nom d’utilisateur","Groupe","Rôle","Demandé le","État d’inscription","État du compte"],loading:"Chargement...",empty:"Aucun résultat.",loginRequired:"Connexion requise.",loadFailed:"Impossible de charger la liste des utilisateurs.",detailForm:{title:"Détails de l’utilisateur",subtitle:"Gérer l’approbation et l’état du compte.",back:"Retour à la liste",loading:"Chargement...",invalidId:"L’identifiant utilisateur est incorrect.",loadFailed:"Impossible de charger les détails.",actionError:"Une erreur est survenue pendant le traitement.",updated:"Les informations utilisateur ont été mises à jour.",deleted:"L’utilisateur a été supprimé.",approved:"La demande d’inscription a été approuvée.",rejected:"La demande d’inscription a été refusée.",info:"Informations de base",account:"Compte utilisateur",name:"Nom d’utilisateur",server:"Serveur",defaultServer:"Serveur par défaut",group:"Groupe",requestedAt:"Demandé le",signupStatus:"État d’inscription",accountStatus:"État du compte",language:"Langue",comment:"Commentaire",approveTitle:"Approuver l’utilisateur",editTitle:"Modifier l’utilisateur",role:"Rôle",approve:"Approuver",reject:"Refuser",save:"Enregistrer",cannotDelete:"Suppression impossible",delete:"Supprimer",currentRole:"Rôle sélectionné : {role}",groupHint:"Après le changement de groupe, seuls les bots de ce groupe sont accessibles."}},
  de:{title:"Benutzerverwaltung",searchPlaceholder:"Nach Benutzerkonto oder Name suchen.",allGroups:"Alle Gruppen",allRoles:"Alle Rollen",allAccountStatuses:"Alle Kontostatus",allSignupStatuses:"Alle Registrierungsstatus",roleNames:{curator:"Kurator",operation_manager:"Betriebsmanager",system_manager:"Systemadministrator",it_admin:"IT-Administrator"},accountStatuses:{active:"Aktiv",locked:"Gesperrt",password_reset:"Passwort zurücksetzen",inactive:"Inaktiv"},signupStatuses:{approved:"Genehmigt",pending:"Genehmigung ausstehend",rejected:"Abgelehnt"},search:"Suchen",total:"Gesamt {count}",perPage:"{count} pro Seite",selected:"{count} ausgewählt",goToLogin:"Zur Anmeldung",selectUser:"{loginId} auswählen",selectAll:"Alle auswählen",columns:["","Benutzerkonto","Benutzername","Gruppe","Rolle","Beantragt am","Registrierungsstatus","Kontostatus"],loading:"Wird geladen...",empty:"Keine Ergebnisse.",loginRequired:"Anmeldung erforderlich.",loadFailed:"Benutzerliste konnte nicht geladen werden.",detailForm:{title:"Benutzerdetails",subtitle:"Benutzergenehmigung und Kontostatus verwalten.",back:"Zur Liste",loading:"Wird geladen...",invalidId:"Die Benutzerkennung ist ungültig.",loadFailed:"Details konnten nicht geladen werden.",actionError:"Bei der Verarbeitung ist ein Fehler aufgetreten.",updated:"Benutzerinformationen wurden aktualisiert.",deleted:"Der Benutzer wurde gelöscht.",approved:"Die Registrierungsanfrage wurde genehmigt.",rejected:"Die Registrierungsanfrage wurde abgelehnt.",info:"Basisinformationen",account:"Benutzerkonto",name:"Benutzername",server:"Server",defaultServer:"Standardserver",group:"Gruppe",requestedAt:"Beantragt am",signupStatus:"Registrierungsstatus",accountStatus:"Kontostatus",language:"Sprache",comment:"Kommentar",approveTitle:"Benutzer genehmigen",editTitle:"Benutzer bearbeiten",role:"Rolle",approve:"Genehmigen",reject:"Ablehnen",save:"Speichern",cannotDelete:"Löschen nicht möglich",delete:"Löschen",currentRole:"Ausgewählte Rolle: {role}",groupHint:"Nach dem Gruppenwechsel sind nur Bots dieser Gruppe zugänglich."}},
} satisfies Record<SupportedLanguage, AdminUsersCatalog>;

export function formatAdminUsersText(template:string, values:Record<string,string|number>) {
  return template.replace(/\{(\w+)\}/g, (_, key:string) => String(values[key] ?? ""));
}

const LEGACY_ACCOUNT_STATUS_ALIASES:Record<string,string> = { active:"active", inactive:"inactive", locked:"locked", password_reset:"password_reset", "활성":"active", "비활성":"inactive", "잠김":"locked", "비밀번호 초기화":"password_reset" };
const LEGACY_SIGNUP_STATUS_ALIASES:Record<string,string> = { approved:"approved", pending:"pending", rejected:"rejected", "계정 승인":"approved", "승인 요청":"pending", "승인 반려":"rejected" };

export function resolveAdminAccountStatus(value:string) { return LEGACY_ACCOUNT_STATUS_ALIASES[value] ?? "inactive"; }
export function resolveAdminSignupStatus(value:string) { return LEGACY_SIGNUP_STATUS_ALIASES[value] ?? value; }
export function legacyAdminAccountStatusLabel(value:string) {
  return value === "active" ? "활성" : value === "locked" ? "잠김" : value === "password_reset" ? "비밀번호 초기화" : "비활성";
}
export function isDefaultOrganizationName(value:string) { return value === "기본 테넌트"; }
