import type { SupportedLanguage } from "@/lib/language";

export type AdminGroupsCatalog = {
  title:string; searchPlaceholder:string; loading:string; total:string; columns:string[]; create:string;
  goToLogin:string; loginRequired:string; loadFailed:string; statuses:Record<string,string>;
  createForm:{title:string;subtitle:string;back:string;name:string;placeholder:string;submitting:string;submit:string;submitError:string};
  detailForm:{title:string;subtitle:string;back:string;loading:string;invalidId:string;loadFailed:string;updateError:string;deleteError:string;info:string;groupId:string;userCount:string;creator:string;updater:string;createdAt:string;updatedAt:string;edit:string;name:string;enabled:string;saving:string;save:string;delete:string;hintAccess:string;hintDelete:string};
};

export const ADMIN_GROUPS_CATALOGS = {
  ko:{title:"그룹 관리",searchPlaceholder:"그룹 아이디 또는 그룹 이름을 검색하세요.",loading:"불러오는 중",total:"전체 {count}건",columns:["그룹 아이디","그룹 이름","사용여부","생성자","최종수정자","최종수정일시"],create:"+ 그룹 생성",goToLogin:"로그인으로 이동",loginRequired:"로그인이 필요합니다.",loadFailed:"그룹 목록을 불러오지 못했습니다.",statuses:{active:"사용",inactive:"미사용"},createForm:{title:"그룹 생성",subtitle:"현재 서버에 속한 새 그룹을 생성합니다.",back:"목록으로",name:"그룹 이름",placeholder:"그룹 이름을 입력하세요.",submitting:"생성 중...",submit:"그룹 생성",submitError:"그룹 생성 중 오류가 발생했습니다."},detailForm:{title:"그룹 상세",subtitle:"현재 서버에 속한 그룹 정보를 확인하고 수정합니다.",back:"목록으로",loading:"불러오는 중입니다...",invalidId:"그룹 식별 정보가 올바르지 않습니다.",loadFailed:"그룹 정보를 불러오지 못했습니다.",updateError:"그룹 수정 중 오류가 발생했습니다.",deleteError:"그룹 삭제 중 오류가 발생했습니다.",info:"기본 정보",groupId:"그룹 아이디",userCount:"사용자 수",creator:"생성자",updater:"최종수정자",createdAt:"생성일시",updatedAt:"최종수정일시",edit:"그룹 수정",name:"그룹 이름",enabled:"사용 여부",saving:"저장 중...",save:"저장",delete:"삭제",hintAccess:"그룹 사용 여부를 변경하면 이 그룹에 속한 사용자의 봇 접근 범위에 영향을 줍니다.",hintDelete:"그룹에 사용자, 봇, API가 연결되어 있으면 삭제되지 않아야 하며 현재는 서버 검증 결과를 그대로 따릅니다."}},
  en:{title:"Group Management",searchPlaceholder:"Search by group ID or name.",loading:"Loading",total:"Total {count}",columns:["Group ID","Group Name","Status","Created By","Updated By","Updated At"],create:"+ Create Group",goToLogin:"Go to login",loginRequired:"Login is required.",loadFailed:"Could not load the group list.",statuses:{active:"Active",inactive:"Inactive"},createForm:{title:"Create Group",subtitle:"Create a new group on the current server.",back:"Back to list",name:"Group name",placeholder:"Enter a group name.",submitting:"Creating...",submit:"Create Group",submitError:"An error occurred while creating the group."},detailForm:{title:"Group Details",subtitle:"Review and edit group information on the current server.",back:"Back to list",loading:"Loading...",invalidId:"The group identifier is invalid.",loadFailed:"Could not load group information.",updateError:"An error occurred while updating the group.",deleteError:"An error occurred while deleting the group.",info:"Basic Information",groupId:"Group ID",userCount:"Users",creator:"Created By",updater:"Updated By",createdAt:"Created At",updatedAt:"Updated At",edit:"Edit Group",name:"Group Name",enabled:"Status",saving:"Saving...",save:"Save",delete:"Delete",hintAccess:"Changing group status affects bot access for users in this group.",hintDelete:"A group linked to users, bots, or APIs should not be deleted; the server validation result is applied."}},
  "zh-CN":{title:"组管理",searchPlaceholder:"按组ID或组名搜索。",loading:"加载中",total:"共{count}项",columns:["组ID","组名","状态","创建者","最后修改者","最后修改时间"],create:"+ 创建组",goToLogin:"前往登录",loginRequired:"需要登录。",loadFailed:"无法加载组列表。",statuses:{active:"启用",inactive:"停用"},createForm:{title:"创建组",subtitle:"在当前服务器创建新组。",back:"返回列表",name:"组名",placeholder:"请输入组名。",submitting:"创建中...",submit:"创建组",submitError:"创建组时发生错误。"},detailForm:{title:"组详情",subtitle:"查看并修改当前服务器的组信息。",back:"返回列表",loading:"加载中...",invalidId:"组标识信息无效。",loadFailed:"无法加载组信息。",updateError:"修改组时发生错误。",deleteError:"删除组时发生错误。",info:"基本信息",groupId:"组ID",userCount:"用户数",creator:"创建者",updater:"最后修改者",createdAt:"创建时间",updatedAt:"最后修改时间",edit:"修改组",name:"组名",enabled:"状态",saving:"保存中...",save:"保存",delete:"删除",hintAccess:"更改组状态会影响该组用户的机器人访问范围。",hintDelete:"连接了用户、机器人或API的组不应删除，最终以服务器验证结果为准。"}},
  ja:{title:"グループ管理",searchPlaceholder:"グループIDまたは名前で検索します。",loading:"読み込み中",total:"全{count}件",columns:["グループID","グループ名","使用状態","作成者","最終更新者","最終更新日時"],create:"+ グループ作成",goToLogin:"ログインへ",loginRequired:"ログインが必要です。",loadFailed:"グループ一覧を取得できませんでした。",statuses:{active:"使用",inactive:"未使用"},createForm:{title:"グループ作成",subtitle:"現在のサーバーに新しいグループを作成します。",back:"一覧へ",name:"グループ名",placeholder:"グループ名を入力してください。",submitting:"作成中...",submit:"グループ作成",submitError:"グループ作成中にエラーが発生しました。"},detailForm:{title:"グループ詳細",subtitle:"現在のサーバーのグループ情報を確認・修正します。",back:"一覧へ",loading:"読み込み中...",invalidId:"グループ識別情報が正しくありません。",loadFailed:"グループ情報を取得できませんでした。",updateError:"グループ更新中にエラーが発生しました。",deleteError:"グループ削除中にエラーが発生しました。",info:"基本情報",groupId:"グループID",userCount:"ユーザー数",creator:"作成者",updater:"最終更新者",createdAt:"作成日時",updatedAt:"最終更新日時",edit:"グループ修正",name:"グループ名",enabled:"使用状態",saving:"保存中...",save:"保存",delete:"削除",hintAccess:"グループの使用状態を変更すると所属ユーザーのボットアクセス範囲に影響します。",hintDelete:"ユーザー、ボット、APIが接続されたグループは削除されず、サーバー検証結果に従います。"}},
  vi:{title:"Quản lý nhóm",searchPlaceholder:"Tìm theo ID hoặc tên nhóm.",loading:"Đang tải",total:"Tổng {count}",columns:["ID nhóm","Tên nhóm","Trạng thái","Người tạo","Người cập nhật","Thời gian cập nhật"],create:"+ Tạo nhóm",goToLogin:"Đến đăng nhập",loginRequired:"Cần đăng nhập.",loadFailed:"Không thể tải danh sách nhóm.",statuses:{active:"Hoạt động",inactive:"Không hoạt động"},createForm:{title:"Tạo nhóm",subtitle:"Tạo nhóm mới trên máy chủ hiện tại.",back:"Về danh sách",name:"Tên nhóm",placeholder:"Nhập tên nhóm.",submitting:"Đang tạo...",submit:"Tạo nhóm",submitError:"Đã xảy ra lỗi khi tạo nhóm."},detailForm:{title:"Chi tiết nhóm",subtitle:"Xem và sửa thông tin nhóm trên máy chủ hiện tại.",back:"Về danh sách",loading:"Đang tải...",invalidId:"Thông tin định danh nhóm không hợp lệ.",loadFailed:"Không thể tải thông tin nhóm.",updateError:"Đã xảy ra lỗi khi cập nhật nhóm.",deleteError:"Đã xảy ra lỗi khi xóa nhóm.",info:"Thông tin cơ bản",groupId:"ID nhóm",userCount:"Số người dùng",creator:"Người tạo",updater:"Người cập nhật",createdAt:"Thời gian tạo",updatedAt:"Thời gian cập nhật",edit:"Sửa nhóm",name:"Tên nhóm",enabled:"Trạng thái",saving:"Đang lưu...",save:"Lưu",delete:"Xóa",hintAccess:"Thay đổi trạng thái nhóm ảnh hưởng đến phạm vi truy cập bot của người dùng trong nhóm.",hintDelete:"Nhóm liên kết với người dùng, bot hoặc API không nên bị xóa; kết quả xác thực máy chủ được áp dụng."}},
  fr:{title:"Gestion des groupes",searchPlaceholder:"Rechercher par identifiant ou nom de groupe.",loading:"Chargement",total:"Total {count}",columns:["ID du groupe","Nom du groupe","État","Créateur","Dernière modification par","Modifié le"],create:"+ Créer un groupe",goToLogin:"Aller à la connexion",loginRequired:"Connexion requise.",loadFailed:"Impossible de charger la liste des groupes.",statuses:{active:"Actif",inactive:"Inactif"},createForm:{title:"Créer un groupe",subtitle:"Créer un nouveau groupe sur le serveur actuel.",back:"Retour à la liste",name:"Nom du groupe",placeholder:"Saisissez un nom de groupe.",submitting:"Création...",submit:"Créer le groupe",submitError:"Une erreur est survenue lors de la création du groupe."},detailForm:{title:"Détails du groupe",subtitle:"Consulter et modifier le groupe du serveur actuel.",back:"Retour à la liste",loading:"Chargement...",invalidId:"L’identifiant du groupe est incorrect.",loadFailed:"Impossible de charger le groupe.",updateError:"Une erreur est survenue lors de la modification du groupe.",deleteError:"Une erreur est survenue lors de la suppression du groupe.",info:"Informations de base",groupId:"ID du groupe",userCount:"Utilisateurs",creator:"Créateur",updater:"Dernière modification par",createdAt:"Créé le",updatedAt:"Modifié le",edit:"Modifier le groupe",name:"Nom du groupe",enabled:"État",saving:"Enregistrement...",save:"Enregistrer",delete:"Supprimer",hintAccess:"Modifier l’état du groupe affecte l’accès aux bots de ses utilisateurs.",hintDelete:"Un groupe lié à des utilisateurs, bots ou API ne doit pas être supprimé ; la validation du serveur s’applique."}},
  de:{title:"Gruppenverwaltung",searchPlaceholder:"Nach Gruppen-ID oder Name suchen.",loading:"Wird geladen",total:"Gesamt {count}",columns:["Gruppen-ID","Gruppenname","Status","Ersteller","Zuletzt geändert von","Geändert am"],create:"+ Gruppe erstellen",goToLogin:"Zur Anmeldung",loginRequired:"Anmeldung erforderlich.",loadFailed:"Gruppenliste konnte nicht geladen werden.",statuses:{active:"Aktiv",inactive:"Inaktiv"},createForm:{title:"Gruppe erstellen",subtitle:"Eine neue Gruppe auf dem aktuellen Server erstellen.",back:"Zur Liste",name:"Gruppenname",placeholder:"Gruppennamen eingeben.",submitting:"Wird erstellt...",submit:"Gruppe erstellen",submitError:"Beim Erstellen der Gruppe ist ein Fehler aufgetreten."},detailForm:{title:"Gruppendetails",subtitle:"Gruppeninformationen auf dem aktuellen Server anzeigen und bearbeiten.",back:"Zur Liste",loading:"Wird geladen...",invalidId:"Die Gruppenkennung ist ungültig.",loadFailed:"Gruppeninformationen konnten nicht geladen werden.",updateError:"Beim Aktualisieren der Gruppe ist ein Fehler aufgetreten.",deleteError:"Beim Löschen der Gruppe ist ein Fehler aufgetreten.",info:"Basisinformationen",groupId:"Gruppen-ID",userCount:"Benutzer",creator:"Ersteller",updater:"Zuletzt geändert von",createdAt:"Erstellt am",updatedAt:"Geändert am",edit:"Gruppe bearbeiten",name:"Gruppenname",enabled:"Status",saving:"Wird gespeichert...",save:"Speichern",delete:"Löschen",hintAccess:"Eine Statusänderung beeinflusst den Bot-Zugriff der Benutzer dieser Gruppe.",hintDelete:"Eine mit Benutzern, Bots oder APIs verknüpfte Gruppe sollte nicht gelöscht werden; die Servervalidierung gilt."}},
} satisfies Record<SupportedLanguage, AdminGroupsCatalog>;

export function formatAdminGroupsText(template:string, values:Record<string,string|number>) {
  return template.replace(/\{(\w+)\}/g, (_, key:string) => String(values[key] ?? ""));
}
