import type { SupportedLanguage } from "@/lib/language";

export type AiOptionTranslationCatalog = Record<string, string>;

export const AI_OPTION_TRANSLATIONS = {
  ko: { "Next: configure using the selected input structure.": "선택한 입력 구조로 구성을 계속합니다.", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "봇 이름에는 모든 언어의 문자, 숫자, 공백과 지원 특수문자를 사용할 수 있습니다." },
  en: { "Next: configure using the selected input structure.": "Continue configuration with the selected input structure.", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "Bot names may contain letters from any language, numbers, spaces, and supported symbols.",
    "1.0/1.5 지원": "Supported in 1.0/1.5", "Aidot 자체 Vector DB": "Aidot built-in Vector DB", "외부 임베딩 + Local Vector DB": "External embedding + Local Vector DB", "1.5 설정": "1.5 configuration", "1.0 지원": "Supported in 1.0", "Local Vector DB": "Local Vector DB", "Aidot Vector Worker 기본 모델": "Aidot Vector Worker default model", "한국어 일반 문서": "General Korean documents", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "Suitable for general Korean documents such as short FAQs, notices, and support answers.", "다국어/표·서식": "Multilingual/tables/forms", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "Suitable for English, multilingual, and table- or form-heavy documents.", "긴 문서/약관": "Long documents/terms", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "Suitable for long semantic searches such as policies, manuals, and long PDFs.", "Ollama 임베딩": "Ollama embedding", "LLM Engine 기본 모델": "LLM Engine default model", "정해진 답변": "Fixed answer", "Semantic Engine RAG 답변": "Semantic Engine RAG answer", "LLM Engine RAG 답변": "LLM Engine RAG answer", "LLM Engine 답변": "LLM Engine answer", "빠른 응답": "Fast response", "고품질 응답": "High-quality response", "기본": "Default", "고품질": "High quality", "대체": "Alternative", "균형": "Balanced", "자동 선택": "Automatic selection", "OpenAI 경유": "Via OpenAI", "실행/학습 가능": "Runnable/trainable", "사용 못함": "Unavailable", "설정 저장만 가능": "Configuration only", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "This combination is connected to the current 1.0 runtime and training engine.", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "This combination is not supported. Select another answer engine.", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "The model can be changed before training and is locked to that engine after training.",
  },
  "zh-CN": { "Next: configure using the selected input structure.": "使用所选输入结构继续配置。", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "机器人名称可以包含任意语言文字、数字、空格和支持的符号。",
    "1.0/1.5 지원": "支持 1.0/1.5", "Aidot 자체 Vector DB": "Aidot 内置 Vector DB", "외부 임베딩 + Local Vector DB": "外部嵌入 + Local Vector DB", "1.5 설정": "1.5 配置", "1.0 지원": "支持 1.0", "Aidot Vector Worker 기본 모델": "Aidot Vector Worker 默认模型", "한국어 일반 문서": "通用韩文文档", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "适合短 FAQ、通知和客服回答等通用韩文文档检索。", "다국어/표·서식": "多语言/表格/格式", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "适合英文、多语言以及包含大量表格和格式的文档。", "긴 문서/약관": "长文档/条款", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "适合保险条款、手册和长 PDF 等长文本语义检索。", "Ollama 임베딩": "Ollama 嵌入", "LLM Engine 기본 모델": "LLM Engine 默认模型", "정해진 답변": "固定回答", "Semantic Engine RAG 답변": "Semantic Engine RAG 回答", "LLM Engine RAG 답변": "LLM Engine RAG 回答", "LLM Engine 답변": "LLM Engine 回答", "빠른 응답": "快速响应", "고품질 응답": "高质量响应", "기본": "默认", "고품질": "高质量", "대체": "备选", "균형": "均衡", "자동 선택": "自动选择", "OpenAI 경유": "通过 OpenAI", "실행/학습 가능": "可运行/训练", "사용 못함": "不可用", "설정 저장만 가능": "仅保存配置", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "该组合已连接当前 1.0 运行时和训练引擎。", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "该组合不可用，请选择其他回答引擎。", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "训练前可更改模型，训练完成后将锁定到该引擎。",
  },
  ja: { "Next: configure using the selected input structure.": "選択した入力構造で構成を続けます。", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "ボット名にはすべての言語の文字、数字、空白、対応記号を使用できます。",
    "1.0/1.5 지원": "1.0/1.5 対応", "Aidot 자체 Vector DB": "Aidot 内蔵 Vector DB", "외부 임베딩 + Local Vector DB": "外部埋め込み + Local Vector DB", "1.5 설정": "1.5 設定", "1.0 지원": "1.0 対応", "Aidot Vector Worker 기본 모델": "Aidot Vector Worker 既定モデル", "한국어 일반 문서": "一般的な韓国語文書", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "短いFAQ、案内、サポート回答など一般的な韓国語文書の検索に適しています。", "다국어/표·서식": "多言語/表/書式", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "英語、多言語、表や書式の多い文書の検索に適しています。", "긴 문서/약관": "長文書/約款", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "保険約款、マニュアル、長いPDFなど長文の意味検索に適しています。", "Ollama 임베딩": "Ollama 埋め込み", "LLM Engine 기본 모델": "LLM Engine 既定モデル", "정해진 답변": "固定回答", "Semantic Engine RAG 답변": "Semantic Engine RAG 回答", "LLM Engine RAG 답변": "LLM Engine RAG 回答", "LLM Engine 답변": "LLM Engine 回答", "빠른 응답": "高速応答", "고품질 응답": "高品質応答", "기본": "既定", "고품질": "高品質", "대체": "代替", "균형": "バランス", "자동 선택": "自動選択", "OpenAI 경유": "OpenAI 経由", "실행/학습 가능": "実行/学習可能", "사용 못함": "使用不可", "설정 저장만 가능": "設定保存のみ", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "現在の1.0ランタイムと学習エンジンに接続された組み合わせです。", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "使用できない組み合わせです。別の回答エンジンを選択してください。", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "学習前はモデルを変更でき、学習完了後はそのエンジンに固定されます。",
  },
  vi: { "Next: configure using the selected input structure.": "Tiếp tục cấu hình với cấu trúc đầu vào đã chọn.", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "Tên bot có thể chứa chữ cái của mọi ngôn ngữ, số, khoảng trắng và ký hiệu được hỗ trợ.",
    "1.0/1.5 지원": "Hỗ trợ 1.0/1.5", "Aidot 자체 Vector DB": "Vector DB tích hợp của Aidot", "외부 임베딩 + Local Vector DB": "Embedding ngoài + Local Vector DB", "1.5 설정": "Cấu hình 1.5", "1.0 지원": "Hỗ trợ 1.0", "Aidot Vector Worker 기본 모델": "Mô hình mặc định Aidot Vector Worker", "한국어 일반 문서": "Tài liệu tiếng Hàn thông dụng", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "Phù hợp để tìm FAQ ngắn, thông báo và câu trả lời hỗ trợ bằng tiếng Hàn.", "다국어/표·서식": "Đa ngôn ngữ/bảng/biểu mẫu", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "Phù hợp với tài liệu tiếng Anh, đa ngôn ngữ, nhiều bảng và biểu mẫu.", "긴 문서/약관": "Tài liệu dài/điều khoản", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "Phù hợp với điều khoản, hướng dẫn và PDF dài cần tìm kiếm ngữ nghĩa.", "Ollama 임베딩": "Embedding Ollama", "LLM Engine 기본 모델": "Mô hình mặc định LLM Engine", "정해진 답변": "Câu trả lời cố định", "Semantic Engine RAG 답변": "Câu trả lời Semantic Engine RAG", "LLM Engine RAG 답변": "Câu trả lời LLM Engine RAG", "LLM Engine 답변": "Câu trả lời LLM Engine", "빠른 응답": "Phản hồi nhanh", "고품질 응답": "Phản hồi chất lượng cao", "기본": "Mặc định", "고품질": "Chất lượng cao", "대체": "Thay thế", "균형": "Cân bằng", "자동 선택": "Tự động chọn", "OpenAI 경유": "Qua OpenAI", "실행/학습 가능": "Có thể chạy/huấn luyện", "사용 못함": "Không khả dụng", "설정 저장만 가능": "Chỉ lưu cấu hình", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "Tổ hợp này được kết nối với runtime và engine huấn luyện 1.0 hiện tại.", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "Tổ hợp này không được hỗ trợ. Hãy chọn engine trả lời khác.", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "Có thể đổi mô hình trước khi huấn luyện và sẽ khóa theo engine sau khi hoàn tất.",
  },
  fr: { "Next: configure using the selected input structure.": "Poursuivez la configuration avec la structure d'entrée sélectionnée.", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "Le nom du bot peut contenir des lettres de toutes les langues, des chiffres, des espaces et les symboles pris en charge.",
    "1.0/1.5 지원": "Pris en charge en 1.0/1.5", "Aidot 자체 Vector DB": "Vector DB intégrée à Aidot", "외부 임베딩 + Local Vector DB": "Embedding externe + Local Vector DB", "1.5 설정": "Configuration 1.5", "1.0 지원": "Pris en charge en 1.0", "Aidot Vector Worker 기본 모델": "Modèle par défaut Aidot Vector Worker", "한국어 일반 문서": "Documents coréens généraux", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "Adapté aux FAQ courtes, avis et réponses d'assistance en coréen.", "다국어/표·서식": "Multilingue/tableaux/formulaires", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "Adapté aux documents anglais, multilingues et riches en tableaux ou formulaires.", "긴 문서/약관": "Documents longs/conditions", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "Adapté aux conditions, manuels et longs PDF nécessitant une recherche sémantique.", "Ollama 임베딩": "Embedding Ollama", "LLM Engine 기본 모델": "Modèle par défaut LLM Engine", "정해진 답변": "Réponse fixe", "Semantic Engine RAG 답변": "Réponse Semantic Engine RAG", "LLM Engine RAG 답변": "Réponse LLM Engine RAG", "LLM Engine 답변": "Réponse LLM Engine", "빠른 응답": "Réponse rapide", "고품질 응답": "Réponse de haute qualité", "기본": "Par défaut", "고품질": "Haute qualité", "대체": "Alternative", "균형": "Équilibré", "자동 선택": "Sélection automatique", "OpenAI 경유": "Via OpenAI", "실행/학습 가능": "Exécutable/entraînable", "사용 못함": "Indisponible", "설정 저장만 가능": "Configuration uniquement", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "Cette combinaison est reliée au runtime et au moteur d'entraînement 1.0 actuels.", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "Cette combinaison n'est pas prise en charge. Sélectionnez un autre moteur de réponse.", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "Le modèle peut être modifié avant l'entraînement puis est verrouillé sur ce moteur.",
  },
  de: { "Next: configure using the selected input structure.": "Konfiguration mit der ausgewählten Eingabestruktur fortsetzen.", "Bot names may contain Unicode letters, numbers, spaces, and supported symbols.": "Bot-Namen dürfen Buchstaben aller Sprachen, Zahlen, Leerzeichen und unterstützte Symbole enthalten.",
    "1.0/1.5 지원": "Unterstützt in 1.0/1.5", "Aidot 자체 Vector DB": "Integrierte Aidot Vector DB", "외부 임베딩 + Local Vector DB": "Externes Embedding + Local Vector DB", "1.5 설정": "1.5-Konfiguration", "1.0 지원": "Unterstützt in 1.0", "Aidot Vector Worker 기본 모델": "Aidot Vector Worker-Standardmodell", "한국어 일반 문서": "Allgemeine koreanische Dokumente", "짧은 FAQ, 안내문, 상담 답변처럼 일반적인 한국어 문서 검색에 적합합니다.": "Geeignet für kurze FAQs, Hinweise und Support-Antworten auf Koreanisch.", "다국어/표·서식": "Mehrsprachig/Tabellen/Formulare", "영문, 다국어, 표와 서식이 많은 문서 검색에 적합합니다.": "Geeignet für englische, mehrsprachige sowie tabellen- und formularreiche Dokumente.", "긴 문서/약관": "Lange Dokumente/Bedingungen", "보험약관, 매뉴얼, 긴 PDF처럼 장문 의미 검색이 중요한 문서에 적합합니다.": "Geeignet für Bedingungen, Handbücher und lange PDFs mit semantischer Suche.", "Ollama 임베딩": "Ollama-Embedding", "LLM Engine 기본 모델": "LLM Engine-Standardmodell", "정해진 답변": "Feste Antwort", "Semantic Engine RAG 답변": "Semantic Engine RAG-Antwort", "LLM Engine RAG 답변": "LLM Engine RAG-Antwort", "LLM Engine 답변": "LLM Engine-Antwort", "빠른 응답": "Schnelle Antwort", "고품질 응답": "Hochwertige Antwort", "기본": "Standard", "고품질": "Hohe Qualität", "대체": "Alternative", "균형": "Ausgewogen", "자동 선택": "Automatische Auswahl", "OpenAI 경유": "Über OpenAI", "실행/학습 가능": "Ausführbar/trainierbar", "사용 못함": "Nicht verfügbar", "설정 저장만 가능": "Nur Konfiguration", "현재 1.0 런타임과 학습 엔진에 연결된 조합입니다.": "Diese Kombination ist mit der aktuellen 1.0-Laufzeit und Trainings-Engine verbunden.", "논리적으로 사용할 수 없는 조합입니다. 다른 답변 엔진을 선택해주세요.": "Diese Kombination wird nicht unterstützt. Wählen Sie eine andere Antwort-Engine.", "학습 전까지 모델을 변경할 수 있고, 학습 완료 후 해당 엔진 기준으로 고정됩니다.": "Das Modell kann vor dem Training geändert werden und wird danach an diese Engine gebunden.",
  },
} satisfies Record<SupportedLanguage, AiOptionTranslationCatalog>;

export function translateAiOptionText(language: SupportedLanguage, text: string): string {
  const catalog: AiOptionTranslationCatalog = AI_OPTION_TRANSLATIONS[language];
  return catalog[text] ?? text;
}
