import type { SupportedLanguage } from "@/lib/language";

export type BotSettingsCatalog = {
  saved: string; saveError: string; cancel: string; saving: string; save: string;
  basicInfo: string; type: string; botId: string; recentModified: string; creationInfo: string;
  fixedAtCreation: string; modelLocked: string; modelChangeable: string; fixedModeMessage: string;
  profile: string; versionCount: string; useStatus: string; searchApiUrl: string; indexName: string; optionalInput: string;
  scoringTitle: string; scoringDescription: string; dictionaryRepresentative: string; entity: string; nounVerb: string;
  characterFragment: string; particleEnding: string; keyMatchMinimum: string; introduction: string; lockedAfterTraining: string;
};

export const BOT_SETTINGS_CATALOGS = {
  ko: { saved: "봇 설정이 저장되었습니다.", saveError: "봇 설정 저장 중 오류가 발생했습니다.", cancel: "취소", saving: "저장 중...", save: "저장", basicInfo: "기본 정보", type: "유형", botId: "봇 ID", recentModified: "최근 수정", creationInfo: "생성 정보", fixedAtCreation: "봇 생성 시 고정", modelLocked: "학습 완료 후 고정", modelChangeable: "학습 전 변경 가능", fixedModeMessage: "언어, NLU 방식, 답변 방식은 봇 생성 시 고정됩니다. 모델은 학습 전까지 변경할 수 있고 학습 완료 후에는 고정됩니다.", profile: "프로필", versionCount: "버전 수", useStatus: "사용 여부", searchApiUrl: "검색 API URL", indexName: "Index 이름", optionalInput: "선택 입력", scoringTitle: "구성 자동분류 가중치", scoringDescription: "구성 화면의 의도 후보 분류에서 사전, 개체, 단어, 글자 조각, 조사/어미 반영 비율을 조정합니다.", dictionaryRepresentative: "사전 대표어", entity: "개체", nounVerb: "명사/동사", characterFragment: "글자 조각", particleEnding: "조사/어미", keyMatchMinimum: "대표어 일치 최소점수", introduction: "소개", lockedAfterTraining: "학습 후 고정" },
  en: { saved: "Bot settings were saved.", saveError: "An error occurred while saving bot settings.", cancel: "Cancel", saving: "Saving...", save: "Save", basicInfo: "Basic Information", type: "Type", botId: "Bot ID", recentModified: "Last Modified", creationInfo: "Creation Information", fixedAtCreation: "Fixed when the bot is created", modelLocked: "Locked after training", modelChangeable: "Changeable before training", fixedModeMessage: "Language, NLU type, and answer mode are fixed when the bot is created. Models can be changed before training and are locked after training.", profile: "Profile", versionCount: "Version Count", useStatus: "Enabled", searchApiUrl: "Search API URL", indexName: "Index Name", optionalInput: "Optional", scoringTitle: "Configuration Auto-Classification Weights", scoringDescription: "Adjust dictionary, entity, word, character fragment, and particle/ending weights for intent candidate classification.", dictionaryRepresentative: "Dictionary Representative", entity: "Entity", nounVerb: "Noun/Verb", characterFragment: "Character Fragment", particleEnding: "Particle/Ending", keyMatchMinimum: "Minimum Representative Match Score", introduction: "Introduction", lockedAfterTraining: "Locked after training" },
  "zh-CN": { saved: "机器人设置已保存。", saveError: "保存机器人设置时发生错误。", cancel: "取消", saving: "正在保存...", save: "保存", basicInfo: "基本信息", type: "类型", botId: "机器人 ID", recentModified: "最近修改", creationInfo: "创建信息", fixedAtCreation: "创建机器人时固定", modelLocked: "训练完成后固定", modelChangeable: "训练前可更改", fixedModeMessage: "语言、NLU 方式和回答方式在创建机器人时固定。模型可在训练前更改，训练完成后固定。", profile: "头像", versionCount: "版本数", useStatus: "使用状态", searchApiUrl: "搜索 API URL", indexName: "Index 名称", optionalInput: "可选", scoringTitle: "配置自动分类权重", scoringDescription: "调整意图候选分类中的词典、实体、词语、字符片段和助词/词尾权重。", dictionaryRepresentative: "词典代表词", entity: "实体", nounVerb: "名词/动词", characterFragment: "字符片段", particleEnding: "助词/词尾", keyMatchMinimum: "代表词匹配最低分", introduction: "介绍", lockedAfterTraining: "训练后固定" },
  ja: { saved: "ボット設定を保存しました。", saveError: "ボット設定の保存中にエラーが発生しました。", cancel: "キャンセル", saving: "保存中...", save: "保存", basicInfo: "基本情報", type: "種別", botId: "ボット ID", recentModified: "最終更新", creationInfo: "作成情報", fixedAtCreation: "ボット作成時に固定", modelLocked: "学習完了後に固定", modelChangeable: "学習前は変更可能", fixedModeMessage: "言語、NLU方式、回答方式はボット作成時に固定されます。モデルは学習前まで変更でき、学習完了後に固定されます。", profile: "プロフィール", versionCount: "バージョン数", useStatus: "使用状態", searchApiUrl: "検索 API URL", indexName: "Index名", optionalInput: "任意入力", scoringTitle: "構成自動分類の重み", scoringDescription: "意図候補分類における辞書、エンティティ、単語、文字断片、助詞/語尾の反映比率を調整します。", dictionaryRepresentative: "辞書代表語", entity: "エンティティ", nounVerb: "名詞/動詞", characterFragment: "文字断片", particleEnding: "助詞/語尾", keyMatchMinimum: "代表語一致の最低スコア", introduction: "紹介", lockedAfterTraining: "学習後に固定" },
  vi: { saved: "Đã lưu cài đặt bot.", saveError: "Đã xảy ra lỗi khi lưu cài đặt bot.", cancel: "Hủy", saving: "Đang lưu...", save: "Lưu", basicInfo: "Thông tin cơ bản", type: "Loại", botId: "ID bot", recentModified: "Sửa gần nhất", creationInfo: "Thông tin tạo", fixedAtCreation: "Cố định khi tạo bot", modelLocked: "Khóa sau khi huấn luyện", modelChangeable: "Có thể đổi trước khi huấn luyện", fixedModeMessage: "Ngôn ngữ, kiểu NLU và cách trả lời được cố định khi tạo bot. Mô hình có thể đổi trước khi huấn luyện và sẽ bị khóa sau đó.", profile: "Hồ sơ", versionCount: "Số phiên bản", useStatus: "Trạng thái sử dụng", searchApiUrl: "URL API tìm kiếm", indexName: "Tên Index", optionalInput: "Tùy chọn", scoringTitle: "Trọng số tự động phân loại cấu hình", scoringDescription: "Điều chỉnh trọng số từ điển, thực thể, từ, mảnh ký tự và tiểu từ/đuôi từ khi phân loại ý định.", dictionaryRepresentative: "Từ đại diện từ điển", entity: "Thực thể", nounVerb: "Danh từ/Động từ", characterFragment: "Mảnh ký tự", particleEnding: "Tiểu từ/Đuôi từ", keyMatchMinimum: "Điểm khớp đại diện tối thiểu", introduction: "Giới thiệu", lockedAfterTraining: "Khóa sau huấn luyện" },
  fr: { saved: "Les paramètres du bot ont été enregistrés.", saveError: "Une erreur est survenue lors de l'enregistrement des paramètres.", cancel: "Annuler", saving: "Enregistrement...", save: "Enregistrer", basicInfo: "Informations générales", type: "Type", botId: "ID du bot", recentModified: "Dernière modification", creationInfo: "Informations de création", fixedAtCreation: "Fixé lors de la création du bot", modelLocked: "Verrouillé après l'entraînement", modelChangeable: "Modifiable avant l'entraînement", fixedModeMessage: "La langue, le type NLU et le mode de réponse sont fixés à la création. Les modèles sont modifiables avant l'entraînement puis verrouillés.", profile: "Profil", versionCount: "Nombre de versions", useStatus: "État d'utilisation", searchApiUrl: "URL de l'API de recherche", indexName: "Nom de l'Index", optionalInput: "Facultatif", scoringTitle: "Poids de classification automatique", scoringDescription: "Ajustez les poids du dictionnaire, des entités, des mots, des fragments de caractères et des particules/terminaisons.", dictionaryRepresentative: "Terme représentatif du dictionnaire", entity: "Entité", nounVerb: "Nom/Verbe", characterFragment: "Fragment de caractères", particleEnding: "Particule/Terminaison", keyMatchMinimum: "Score minimal de correspondance", introduction: "Présentation", lockedAfterTraining: "Verrouillé après l'entraînement" },
  de: { saved: "Die Bot-Einstellungen wurden gespeichert.", saveError: "Beim Speichern der Bot-Einstellungen ist ein Fehler aufgetreten.", cancel: "Abbrechen", saving: "Wird gespeichert...", save: "Speichern", basicInfo: "Grundinformationen", type: "Typ", botId: "Bot-ID", recentModified: "Zuletzt geändert", creationInfo: "Erstellungsinformationen", fixedAtCreation: "Bei der Bot-Erstellung festgelegt", modelLocked: "Nach dem Training gesperrt", modelChangeable: "Vor dem Training änderbar", fixedModeMessage: "Sprache, NLU-Typ und Antwortmodus werden bei der Bot-Erstellung festgelegt. Modelle sind vor dem Training änderbar und danach gesperrt.", profile: "Profil", versionCount: "Versionsanzahl", useStatus: "Verwendungsstatus", searchApiUrl: "Such-API-URL", indexName: "Indexname", optionalInput: "Optional", scoringTitle: "Gewichte der automatischen Konfigurationsklassifizierung", scoringDescription: "Passen Sie Wörterbuch-, Entitäts-, Wort-, Zeichenfragment- und Partikel-/Endungsgewichte für die Intent-Klassifizierung an.", dictionaryRepresentative: "Wörterbuch-Repräsentant", entity: "Entität", nounVerb: "Nomen/Verb", characterFragment: "Zeichenfragment", particleEnding: "Partikel/Endung", keyMatchMinimum: "Mindestscore für Repräsentantenübereinstimmung", introduction: "Einführung", lockedAfterTraining: "Nach Training gesperrt" },
} satisfies Record<SupportedLanguage, BotSettingsCatalog>;
