import type { SupportedLanguage } from "@/lib/language";

export type DictionaryEditorCatalog = {
  createTitle:string; editTitle:string; close:string; word:string; synonymRecommendation:string; wordHelp:string; recommendedSynonyms:string; recommendationUnavailable:string; synonymSearch:string; synonym:string; add:string; synonymHelp:string; optionalHelp:string; synonymList:string; delete:string; noSearchResults:string; emptySynonyms:string; intentUsage:string; cancel:string; saving:string; save:string;
  validation:{ required:string; maxLength:string; maxSynonyms:string; duplicateSynonym:string; noActiveVersion:string; duplicateWord:string; duplicateSynonyms:string; sameAsWord:string; saved:string; created:string; updated:string; saveFailed:string };
};

export const DICTIONARY_EDITOR_CATALOGS = {
  ko:{createTitle:"단어 등록",editTitle:"단어 수정",close:"닫기",word:"단어",synonymRecommendation:"동의어 추천",wordHelp:"단어는 100자 이하로 입력합니다. 복합어와 구문도 대표 단어로 등록할 수 있습니다.",recommendedSynonyms:"추천 동의어",recommendationUnavailable:"동의어 추천 기능은 아직 준비 중입니다.",synonymSearch:"동의어 검색",synonym:"동의어",add:"추가",synonymHelp:"동의어는 100자 이하로 입력하고 Enter로 등록합니다. 최대 500개까지 등록할 수 있습니다.",optionalHelp:"동의어는 없어도 저장할 수 있습니다. 대표 단어만 등록하여 복합명사나 구문을 하나의 단어처럼 인식시킬 수 있습니다.",synonymList:"동의어 목록",delete:"삭제",noSearchResults:"검색 조건에 맞는 동의어가 없습니다.",emptySynonyms:"등록된 동의어가 없습니다. 동의어 없이 저장할 수 있습니다.",intentUsage:"의도 사용여부",cancel:"취소",saving:"저장 중...",save:"저장",validation:{required:"{field}을(를) 입력해주세요.",maxLength:"{field}은(는) 100자 이하로 입력해주세요.",maxSynonyms:"동의어는 최대 500개까지 등록할 수 있습니다.",duplicateSynonym:"이미 등록된 동의어입니다.",noActiveVersion:"활성 버전이 없습니다.",duplicateWord:"이미 등록된 단어입니다.",duplicateSynonyms:"중복된 동의어는 등록할 수 없습니다.",sameAsWord:"단어와 동일한 값을 동의어로 등록할 수 없습니다.",saved:"사전이 저장되었습니다.",created:"단어가 등록되었습니다.",updated:"단어가 저장되었습니다.",saveFailed:"사전 저장 중 오류가 발생했습니다."}},
  en:{createTitle:"Add Word",editTitle:"Edit Word",close:"Close",word:"Word",synonymRecommendation:"Recommend Synonyms",wordHelp:"Enter up to 100 characters. Compound words and phrases can be registered as representative words.",recommendedSynonyms:"Recommended Synonyms",recommendationUnavailable:"Synonym recommendations are not available yet.",synonymSearch:"Search Synonyms",synonym:"Synonym",add:"Add",synonymHelp:"Enter up to 100 characters and press Enter. Up to 500 synonyms can be registered.",optionalHelp:"Synonyms are optional. A representative word alone can make a compound noun or phrase recognized as one word.",synonymList:"Synonym List",delete:"Delete",noSearchResults:"No synonyms match the search criteria.",emptySynonyms:"No synonyms are registered. You can save without synonyms.",intentUsage:"Use for Intents",cancel:"Cancel",saving:"Saving...",save:"Save",validation:{required:"Enter {field}.",maxLength:"{field} must be 100 characters or fewer.",maxSynonyms:"Up to 500 synonyms can be registered.",duplicateSynonym:"This synonym is already registered.",noActiveVersion:"No active version is available.",duplicateWord:"This word is already registered.",duplicateSynonyms:"Duplicate synonyms cannot be registered.",sameAsWord:"A synonym cannot be identical to the word.",saved:"The dictionary was saved.",created:"The word was added.",updated:"The word was saved.",saveFailed:"Failed to save the dictionary."}},
  "zh-CN":{createTitle:"添加词",editTitle:"编辑词",close:"关闭",word:"词",synonymRecommendation:"推荐同义词",wordHelp:"请输入不超过100个字符。复合词和短语也可作为代表词注册。",recommendedSynonyms:"推荐同义词",recommendationUnavailable:"同义词推荐功能尚未开放。",synonymSearch:"搜索同义词",synonym:"同义词",add:"添加",synonymHelp:"输入不超过100个字符并按 Enter 注册，最多500个。",optionalHelp:"同义词为可选项。只注册代表词也可将复合名词或短语识别为一个词。",synonymList:"同义词列表",delete:"删除",noSearchResults:"没有符合搜索条件的同义词。",emptySynonyms:"尚未注册同义词，可以不添加同义词直接保存。",intentUsage:"用于意图",cancel:"取消",saving:"保存中...",save:"保存",validation:{required:"请输入{field}。",maxLength:"{field}必须不超过100个字符。",maxSynonyms:"同义词最多可注册500个。",duplicateSynonym:"该同义词已注册。",noActiveVersion:"没有活动版本。",duplicateWord:"该词已注册。",duplicateSynonyms:"不能注册重复的同义词。",sameAsWord:"不能将与代表词相同的值注册为同义词。",saved:"词典已保存。",created:"词已添加。",updated:"词已保存。",saveFailed:"保存词典失败。"}},
  ja:{createTitle:"単語を登録",editTitle:"単語を編集",close:"閉じる",word:"単語",synonymRecommendation:"同義語を推薦",wordHelp:"100文字以内で入力します。複合語やフレーズも代表語として登録できます。",recommendedSynonyms:"おすすめ同義語",recommendationUnavailable:"同義語推薦機能はまだ準備中です。",synonymSearch:"同義語を検索",synonym:"同義語",add:"追加",synonymHelp:"100文字以内で入力し、Enterで登録します。最大500件です。",optionalHelp:"同義語なしでも保存できます。代表語だけで複合名詞やフレーズを一語として認識できます。",synonymList:"同義語一覧",delete:"削除",noSearchResults:"検索条件に一致する同義語がありません。",emptySynonyms:"登録された同義語がありません。同義語なしで保存できます。",intentUsage:"意図で使用",cancel:"キャンセル",saving:"保存中...",save:"保存",validation:{required:"{field}を入力してください。",maxLength:"{field}は100文字以内で入力してください。",maxSynonyms:"同義語は最大500件まで登録できます。",duplicateSynonym:"この同義語は登録済みです。",noActiveVersion:"有効なバージョンがありません。",duplicateWord:"この単語は登録済みです。",duplicateSynonyms:"重複する同義語は登録できません。",sameAsWord:"単語と同じ値を同義語として登録できません。",saved:"辞書を保存しました。",created:"単語を登録しました。",updated:"単語を保存しました。",saveFailed:"辞書の保存に失敗しました。"}},
  vi:{createTitle:"Thêm từ",editTitle:"Sửa từ",close:"Đóng",word:"Từ",synonymRecommendation:"Đề xuất từ đồng nghĩa",wordHelp:"Nhập tối đa 100 ký tự. Có thể đăng ký từ ghép và cụm từ làm từ đại diện.",recommendedSynonyms:"Từ đồng nghĩa đề xuất",recommendationUnavailable:"Tính năng đề xuất từ đồng nghĩa chưa sẵn sàng.",synonymSearch:"Tìm từ đồng nghĩa",synonym:"Từ đồng nghĩa",add:"Thêm",synonymHelp:"Nhập tối đa 100 ký tự và nhấn Enter. Có thể đăng ký tối đa 500 từ.",optionalHelp:"Có thể lưu mà không cần từ đồng nghĩa. Chỉ cần từ đại diện để nhận dạng cụm từ như một từ.",synonymList:"Danh sách từ đồng nghĩa",delete:"Xóa",noSearchResults:"Không có từ đồng nghĩa phù hợp.",emptySynonyms:"Chưa có từ đồng nghĩa. Có thể lưu mà không cần từ đồng nghĩa.",intentUsage:"Dùng cho ý định",cancel:"Hủy",saving:"Đang lưu...",save:"Lưu",validation:{required:"Nhập {field}.",maxLength:"{field} phải có tối đa 100 ký tự.",maxSynonyms:"Có thể đăng ký tối đa 500 từ đồng nghĩa.",duplicateSynonym:"Từ đồng nghĩa này đã được đăng ký.",noActiveVersion:"Không có phiên bản đang hoạt động.",duplicateWord:"Từ này đã được đăng ký.",duplicateSynonyms:"Không thể đăng ký từ đồng nghĩa trùng lặp.",sameAsWord:"Từ đồng nghĩa không được giống từ đại diện.",saved:"Đã lưu từ điển.",created:"Đã thêm từ.",updated:"Đã lưu từ.",saveFailed:"Không thể lưu từ điển."}},
  fr:{createTitle:"Ajouter un mot",editTitle:"Modifier le mot",close:"Fermer",word:"Mot",synonymRecommendation:"Recommander des synonymes",wordHelp:"Saisissez 100 caractères maximum. Les mots composés et expressions peuvent servir de mot principal.",recommendedSynonyms:"Synonymes recommandés",recommendationUnavailable:"La recommandation de synonymes n’est pas encore disponible.",synonymSearch:"Rechercher des synonymes",synonym:"Synonyme",add:"Ajouter",synonymHelp:"Saisissez 100 caractères maximum puis appuyez sur Entrée. Limite : 500 synonymes.",optionalHelp:"Les synonymes sont facultatifs. Un mot principal suffit pour reconnaître une expression comme un seul mot.",synonymList:"Liste des synonymes",delete:"Supprimer",noSearchResults:"Aucun synonyme ne correspond aux critères.",emptySynonyms:"Aucun synonyme enregistré. Vous pouvez enregistrer sans synonyme.",intentUsage:"Utiliser dans les intentions",cancel:"Annuler",saving:"Enregistrement...",save:"Enregistrer",validation:{required:"Saisissez {field}.",maxLength:"{field} doit contenir au maximum 100 caractères.",maxSynonyms:"Vous pouvez enregistrer jusqu’à 500 synonymes.",duplicateSynonym:"Ce synonyme est déjà enregistré.",noActiveVersion:"Aucune version active.",duplicateWord:"Ce mot est déjà enregistré.",duplicateSynonyms:"Les synonymes en double ne peuvent pas être enregistrés.",sameAsWord:"Un synonyme ne peut pas être identique au mot principal.",saved:"Le dictionnaire a été enregistré.",created:"Le mot a été ajouté.",updated:"Le mot a été enregistré.",saveFailed:"Échec de l’enregistrement du dictionnaire."}},
  de:{createTitle:"Wort hinzufügen",editTitle:"Wort bearbeiten",close:"Schließen",word:"Wort",synonymRecommendation:"Synonyme empfehlen",wordHelp:"Geben Sie maximal 100 Zeichen ein. Zusammengesetzte Wörter und Phrasen sind als Hauptwort möglich.",recommendedSynonyms:"Empfohlene Synonyme",recommendationUnavailable:"Synonymempfehlungen sind noch nicht verfügbar.",synonymSearch:"Synonyme suchen",synonym:"Synonym",add:"Hinzufügen",synonymHelp:"Maximal 100 Zeichen eingeben und Enter drücken. Bis zu 500 Synonyme sind möglich.",optionalHelp:"Synonyme sind optional. Ein Hauptwort genügt, um eine Phrase als ein Wort zu erkennen.",synonymList:"Synonymliste",delete:"Löschen",noSearchResults:"Keine Synonyme entsprechen den Suchkriterien.",emptySynonyms:"Keine Synonyme registriert. Speichern ohne Synonyme ist möglich.",intentUsage:"Für Intents verwenden",cancel:"Abbrechen",saving:"Speichern...",save:"Speichern",validation:{required:"Geben Sie {field} ein.",maxLength:"{field} darf höchstens 100 Zeichen lang sein.",maxSynonyms:"Bis zu 500 Synonyme können registriert werden.",duplicateSynonym:"Dieses Synonym ist bereits registriert.",noActiveVersion:"Keine aktive Version vorhanden.",duplicateWord:"Dieses Wort ist bereits registriert.",duplicateSynonyms:"Doppelte Synonyme können nicht registriert werden.",sameAsWord:"Ein Synonym darf nicht dem Hauptwort entsprechen.",saved:"Das Wörterbuch wurde gespeichert.",created:"Das Wort wurde hinzugefügt.",updated:"Das Wort wurde gespeichert.",saveFailed:"Wörterbuch konnte nicht gespeichert werden."}},
} satisfies Record<SupportedLanguage, DictionaryEditorCatalog>;

export function formatDictionaryEditorText(template:string, values:Record<string,string|number>) {
  return template.replace(/\{(\w+)\}/g,(_,key:string)=>String(values[key]??""));
}