import type { SupportedLanguage } from "@/lib/language";
export type EntityValueDialogCatalog = {
  valueCreateTitle: string;
  valueEditTitle: string;
  synonymSearch: string;
  synonymSearchPlaceholder: string;
  add: string;
  synonymList: string;
  noSynonymSearchResults: string;
  emptySynonyms: string;
  pattern: string;
  regexCheck: string;
  patternList: string;
  emptyPatterns: string;
  regexTest: string;
  regexTestPlaceholder: string;
  test: string;
  validRegex: string;
  matchedPatterns: string;
  noMatchedPatterns: string;
  validation: {
    valueRequired: string;
    valueMaxLength: string;
    duplicateValue: string;
    patternRequired: string;
    synonymRequired: string;
    patternMaxLength: string;
    synonymMaxLength: string;
    duplicatePattern: string;
    duplicateSynonym: string;
    invalidRegexWithReason: string;
    regexSyntaxError: string;
    maxPatterns: string;
    patternCheckRequired: string;
    patternRequiredBeforeTest: string;
    testTextRequired: string;
    atLeastOnePattern: string;
    invalidPattern: string;
  };
};
type EntityEditorBaseCatalog={dictionaryImportTitle:string;close:string;total:string;pageSize:string;searchPlaceholder:string;selectAll:string;word:string;synonym:string;selectRow:string;noDictionary:string;cancel:string;import:string;saved:string;saveFailed:string;systemTitle:string;createTitle:string;viewTitle:string;systemEntityDescription:string;category:string;systemEntity:string;dictionaryType:string;standardExpression:string;entityName:string;examples:string;sentenceTest:string;systemPlaceholder:string;extractResult:string;enterTestText:string;noExtractedValue:string;sourceValue:string;targetValue:string;delete:string;importDictionary:string;addEntityValue:string;entityValue:string;type:string;synonymPattern:string;emptyValues:string;saving:string;save:string;validation:{invalidRegex:string}};
export type EntityEditorCatalog = Omit<EntityEditorBaseCatalog, "validation"> & EntityValueDialogCatalog & {
  validation: EntityEditorBaseCatalog["validation"] & EntityValueDialogCatalog["validation"];
};
const ko:EntityEditorBaseCatalog={dictionaryImportTitle:"사전 불러오기",close:"닫기",total:"전체 {count}건",pageSize:"{count}개씩 보기",searchPlaceholder:"개체값, 동의어 또는 패턴을 검색하세요.",selectAll:"전체 선택",word:"단어",synonym:"동의어",selectRow:"{name} 선택",noDictionary:"불러올 수 있는 사전이 없습니다.",cancel:"취소",import:"불러오기",saved:"개체값이 저장되었습니다.",saveFailed:"개체값 저장 중 오류가 발생했습니다.",systemTitle:"{name} 시스템 개체",createTitle:"개체값 조회(개체 생성)",viewTitle:"개체값 조회",systemEntityDescription:"시스템 개체는 CGA 시스템이 제공하는 기본 개체로 수정하거나 삭제할 수 없습니다.",category:"구분",systemEntity:"시스템 개체",dictionaryType:"사전종류",standardExpression:"표준 표현",entityName:"개체명",examples:"예제",sentenceTest:"문장 테스트",systemPlaceholder:"예: 내 전화번호는 010-4350-1234 입니다.",extractResult:"추출 결과",enterTestText:"테스트할 문장을 입력해주세요.",noExtractedValue:"추출된 값이 없습니다.",sourceValue:"원문값",targetValue:"표준값(target)",delete:"삭제",importDictionary:"+ 사전 불러오기",addEntityValue:"+ 개체값 추가",entityValue:"개체값",type:"유형",synonymPattern:"동의어/패턴",emptyValues:"등록된 개체값이 없습니다. 먼저 개체값을 추가해주세요.",saving:"저장 중...",save:"저장",validation:{invalidRegex:"정규식 문법이 올바르지 않습니다."}};
const en:EntityEditorBaseCatalog={dictionaryImportTitle:"Import Dictionary",close:"Close",total:"Total {count}",pageSize:"{count} per page",searchPlaceholder:"Search entity values, synonyms, or patterns.",selectAll:"Select all",word:"Word",synonym:"Synonym",selectRow:"Select {name}",noDictionary:"No dictionary entries are available to import.",cancel:"Cancel",import:"Import",saved:"Entity values were saved.",saveFailed:"Failed to save entity values.",systemTitle:"{name} System Entity",createTitle:"Entity Values (Create Entity)",viewTitle:"Entity Values",systemEntityDescription:"System entities are provided by CGA and cannot be edited or deleted.",category:"Category",systemEntity:"System Entity",dictionaryType:"Dictionary Type",standardExpression:"Standard Expression",entityName:"Entity Name",examples:"Examples",sentenceTest:"Sentence Test",systemPlaceholder:"Example: My phone number is 010-4350-1234.",extractResult:"Extraction Result",enterTestText:"Enter a sentence to test.",noExtractedValue:"No value was extracted.",sourceValue:"Source Value",targetValue:"Standard Value (target)",delete:"Delete",importDictionary:"+ Import Dictionary",addEntityValue:"+ Add Entity Value",entityValue:"Entity Value",type:"Type",synonymPattern:"Synonym/Pattern",emptyValues:"No entity values are registered. Add one first.",saving:"Saving...",save:"Save",validation:{invalidRegex:"The regular expression syntax is invalid."}};
const zh:EntityEditorBaseCatalog={...en,dictionaryImportTitle:"导入词典",close:"关闭",total:"共 {count} 条",pageSize:"每页 {count} 条",searchPlaceholder:"搜索实体值、同义词或模式。",selectAll:"全选",word:"词",synonym:"同义词",selectRow:"选择{name}",noDictionary:"没有可导入的词典项。",cancel:"取消",import:"导入",saved:"实体值已保存。",saveFailed:"保存实体值失败。",systemTitle:"{name} 系统实体",createTitle:"实体值（创建实体）",viewTitle:"实体值",systemEntityDescription:"系统实体由CGA提供，无法修改或删除。",category:"分类",systemEntity:"系统实体",dictionaryType:"词典类型",standardExpression:"标准表达式",entityName:"实体名称",examples:"示例",sentenceTest:"句子测试",systemPlaceholder:"例如：我的电话号码是010-4350-1234。",extractResult:"提取结果",enterTestText:"请输入测试句子。",noExtractedValue:"未提取到值。",sourceValue:"原始值",targetValue:"标准值(target)",delete:"删除",importDictionary:"+ 导入词典",addEntityValue:"+ 添加实体值",entityValue:"实体值",type:"类型",synonymPattern:"同义词/模式",emptyValues:"尚未注册实体值。请先添加。",saving:"保存中...",save:"保存",validation:{invalidRegex:"正则表达式语法无效。"}};
const ja:EntityEditorBaseCatalog={...en,dictionaryImportTitle:"辞書をインポート",close:"閉じる",total:"全 {count} 件",pageSize:"{count}件ずつ表示",searchPlaceholder:"エンティティ値、同義語、パターンを検索します。",selectAll:"すべて選択",word:"単語",synonym:"同義語",selectRow:"{name}を選択",noDictionary:"インポートできる辞書がありません。",cancel:"キャンセル",import:"インポート",saved:"エンティティ値を保存しました。",saveFailed:"エンティティ値を保存できませんでした。",systemTitle:"{name} システムエンティティ",createTitle:"エンティティ値（エンティティ作成）",viewTitle:"エンティティ値",systemEntityDescription:"システムエンティティはCGAが提供し、編集または削除できません。",category:"区分",systemEntity:"システムエンティティ",dictionaryType:"辞書タイプ",standardExpression:"標準表現",entityName:"エンティティ名",examples:"例",sentenceTest:"文テスト",systemPlaceholder:"例：電話番号は010-4350-1234です。",extractResult:"抽出結果",enterTestText:"テストする文を入力してください。",noExtractedValue:"抽出された値がありません。",sourceValue:"原文値",targetValue:"標準値(target)",delete:"削除",importDictionary:"+ 辞書をインポート",addEntityValue:"+ エンティティ値を追加",entityValue:"エンティティ値",type:"タイプ",synonymPattern:"同義語/パターン",emptyValues:"エンティティ値がありません。先に追加してください。",saving:"保存中...",save:"保存",validation:{invalidRegex:"正規表現の構文が正しくありません。"}};
const vi:EntityEditorBaseCatalog={...en,dictionaryImportTitle:"Nhập từ điển",close:"Đóng",total:"Tổng {count}",pageSize:"{count} mỗi trang",searchPlaceholder:"Tìm giá trị thực thể, từ đồng nghĩa hoặc mẫu.",selectAll:"Chọn tất cả",word:"Từ",synonym:"Từ đồng nghĩa",selectRow:"Chọn {name}",noDictionary:"Không có mục từ điển để nhập.",cancel:"Hủy",import:"Nhập",saved:"Đã lưu giá trị thực thể.",saveFailed:"Không thể lưu giá trị thực thể.",systemTitle:"Thực thể hệ thống {name}",createTitle:"Giá trị thực thể (Tạo thực thể)",viewTitle:"Giá trị thực thể",systemEntityDescription:"Thực thể hệ thống do CGA cung cấp và không thể sửa hoặc xóa.",category:"Loại",systemEntity:"Thực thể hệ thống",dictionaryType:"Loại từ điển",standardExpression:"Biểu thức chuẩn",entityName:"Tên thực thể",examples:"Ví dụ",sentenceTest:"Kiểm tra câu",systemPlaceholder:"Ví dụ: Số điện thoại của tôi là 010-4350-1234.",extractResult:"Kết quả trích xuất",enterTestText:"Nhập câu để kiểm tra.",noExtractedValue:"Không trích xuất được giá trị.",sourceValue:"Giá trị gốc",targetValue:"Giá trị chuẩn (target)",delete:"Xóa",importDictionary:"+ Nhập từ điển",addEntityValue:"+ Thêm giá trị",entityValue:"Giá trị thực thể",type:"Loại",synonymPattern:"Từ đồng nghĩa/Mẫu",emptyValues:"Chưa có giá trị thực thể. Hãy thêm trước.",saving:"Đang lưu...",save:"Lưu",validation:{invalidRegex:"Cú pháp biểu thức chính quy không hợp lệ."}};
const fr:EntityEditorBaseCatalog={...en,dictionaryImportTitle:"Importer le dictionnaire",close:"Fermer",total:"Total {count}",pageSize:"{count} par page",searchPlaceholder:"Rechercher une valeur, un synonyme ou un motif.",selectAll:"Tout sélectionner",word:"Mot",synonym:"Synonyme",selectRow:"Sélectionner {name}",noDictionary:"Aucune entrée de dictionnaire à importer.",cancel:"Annuler",import:"Importer",saved:"Les valeurs d’entité ont été enregistrées.",saveFailed:"Échec de l’enregistrement des valeurs.",systemTitle:"Entité système {name}",createTitle:"Valeurs d’entité (Créer l’entité)",viewTitle:"Valeurs d’entité",systemEntityDescription:"Les entités système sont fournies par CGA et ne peuvent être modifiées ou supprimées.",category:"Catégorie",systemEntity:"Entité système",dictionaryType:"Type de dictionnaire",standardExpression:"Expression standard",entityName:"Nom de l’entité",examples:"Exemples",sentenceTest:"Test de phrase",systemPlaceholder:"Exemple : mon numéro est 010-4350-1234.",extractResult:"Résultat de l’extraction",enterTestText:"Saisissez une phrase à tester.",noExtractedValue:"Aucune valeur extraite.",sourceValue:"Valeur source",targetValue:"Valeur standard (target)",delete:"Supprimer",importDictionary:"+ Importer le dictionnaire",addEntityValue:"+ Ajouter une valeur",entityValue:"Valeur d’entité",type:"Type",synonymPattern:"Synonyme/Motif",emptyValues:"Aucune valeur enregistrée. Ajoutez-en une d’abord.",saving:"Enregistrement...",save:"Enregistrer",validation:{invalidRegex:"La syntaxe de l’expression régulière est invalide."}};
const de:EntityEditorBaseCatalog={...en,dictionaryImportTitle:"Wörterbuch importieren",close:"Schließen",total:"Gesamt {count}",pageSize:"{count} pro Seite",searchPlaceholder:"Nach Entitätswert, Synonym oder Muster suchen.",selectAll:"Alle auswählen",word:"Wort",synonym:"Synonym",selectRow:"{name} auswählen",noDictionary:"Keine Wörterbucheinträge zum Importieren.",cancel:"Abbrechen",import:"Importieren",saved:"Entitätswerte wurden gespeichert.",saveFailed:"Entitätswerte konnten nicht gespeichert werden.",systemTitle:"Systementität {name}",createTitle:"Entitätswerte (Entität erstellen)",viewTitle:"Entitätswerte",systemEntityDescription:"Systementitäten werden von CGA bereitgestellt und können nicht bearbeitet oder gelöscht werden.",category:"Kategorie",systemEntity:"Systementität",dictionaryType:"Wörterbuchtyp",standardExpression:"Standardausdruck",entityName:"Entitätsname",examples:"Beispiele",sentenceTest:"Satztest",systemPlaceholder:"Beispiel: Meine Telefonnummer ist 010-4350-1234.",extractResult:"Extraktionsergebnis",enterTestText:"Geben Sie einen Testsatz ein.",noExtractedValue:"Kein Wert extrahiert.",sourceValue:"Quellwert",targetValue:"Standardwert (target)",delete:"Löschen",importDictionary:"+ Wörterbuch importieren",addEntityValue:"+ Entitätswert hinzufügen",entityValue:"Entitätswert",type:"Typ",synonymPattern:"Synonym/Muster",emptyValues:"Keine Entitätswerte registriert. Fügen Sie zuerst einen hinzu.",saving:"Speichern...",save:"Speichern",validation:{invalidRegex:"Die Syntax des regulären Ausdrucks ist ungültig."}};
const entityValueDialogCatalogs = {
  ko: {
    valueCreateTitle: "개체값 생성", valueEditTitle: "개체값 수정", synonymSearch: "동의어 검색", synonymSearchPlaceholder: "동의어를 검색하세요.", add: "추가", synonymList: "동의어 목록", noSynonymSearchResults: "검색 조건에 맞는 동의어가 없습니다.", emptySynonyms: "등록된 동의어가 없습니다.", pattern: "패턴", regexCheck: "정규식 확인", patternList: "패턴 목록", emptyPatterns: "등록된 패턴이 없습니다.", regexTest: "정규식 테스트", regexTestPlaceholder: "테스트할 문장을 입력하세요.", test: "테스트", validRegex: "등록 가능한 정규식입니다.", matchedPatterns: "일치하는 패턴: {patterns}", noMatchedPatterns: "일치하는 패턴이 없습니다.",
    validation: { valueRequired: "개체값을 입력해주세요.", valueMaxLength: "개체값은 100자 이하로 입력해주세요.", duplicateValue: "동일한 이름의 개체값이 등록되어 있습니다.", patternRequired: "패턴을 입력해주세요.", synonymRequired: "동의어를 입력해주세요.", patternMaxLength: "패턴은 256자 이하로 입력해주세요.", synonymMaxLength: "동의어는 100자 이하로 입력해주세요.", duplicatePattern: "동일한 패턴이 등록되어 있습니다.", duplicateSynonym: "동일한 이름의 동의어가 등록되어 있습니다.", invalidRegexWithReason: "'{value}' 정규식이 올바르지 않습니다. {reason}", regexSyntaxError: "정규식 문법 오류: {reason}", maxPatterns: "패턴은 최대 5개까지 등록할 수 있습니다.", patternCheckRequired: "확인할 패턴을 입력해주세요.", patternRequiredBeforeTest: "먼저 패턴을 1개 이상 등록해주세요.", testTextRequired: "테스트할 문장을 입력해주세요.", atLeastOnePattern: "패턴을 1개 이상 등록해주세요.", invalidPattern: "'{value}' 정규식이 올바르지 않습니다." },
  },
  en: {
    valueCreateTitle: "Create Entity Value", valueEditTitle: "Edit Entity Value", synonymSearch: "Search Synonyms", synonymSearchPlaceholder: "Search synonyms.", add: "Add", synonymList: "Synonym List", noSynonymSearchResults: "No synonyms match the search criteria.", emptySynonyms: "No synonyms are registered.", pattern: "Pattern", regexCheck: "Check Regular Expression", patternList: "Pattern List", emptyPatterns: "No patterns are registered.", regexTest: "Regular Expression Test", regexTestPlaceholder: "Enter a sentence to test.", test: "Test", validRegex: "This regular expression can be registered.", matchedPatterns: "Matched patterns: {patterns}", noMatchedPatterns: "No patterns matched.",
    validation: { valueRequired: "Enter an entity value.", valueMaxLength: "Enter no more than 100 characters for the entity value.", duplicateValue: "An entity value with the same name is already registered.", patternRequired: "Enter a pattern.", synonymRequired: "Enter a synonym.", patternMaxLength: "Enter no more than 256 characters for the pattern.", synonymMaxLength: "Enter no more than 100 characters for the synonym.", duplicatePattern: "The same pattern is already registered.", duplicateSynonym: "A synonym with the same name is already registered.", invalidRegexWithReason: "The regular expression '{value}' is invalid. {reason}", regexSyntaxError: "Regular expression syntax error: {reason}", maxPatterns: "You can register up to 5 patterns.", patternCheckRequired: "Enter a pattern to check.", patternRequiredBeforeTest: "Register at least one pattern first.", testTextRequired: "Enter a sentence to test.", atLeastOnePattern: "Register at least one pattern.", invalidPattern: "The regular expression '{value}' is invalid." },
  },
  "zh-CN": {
    valueCreateTitle: "创建实体值", valueEditTitle: "编辑实体值", synonymSearch: "搜索同义词", synonymSearchPlaceholder: "搜索同义词。", add: "添加", synonymList: "同义词列表", noSynonymSearchResults: "没有符合搜索条件的同义词。", emptySynonyms: "尚未注册同义词。", pattern: "模式", regexCheck: "检查正则表达式", patternList: "模式列表", emptyPatterns: "尚未注册模式。", regexTest: "正则表达式测试", regexTestPlaceholder: "请输入测试句子。", test: "测试", validRegex: "该正则表达式可以注册。", matchedPatterns: "匹配的模式：{patterns}", noMatchedPatterns: "没有匹配的模式。",
    validation: { valueRequired: "请输入实体值。", valueMaxLength: "实体值不得超过100个字符。", duplicateValue: "已注册同名实体值。", patternRequired: "请输入模式。", synonymRequired: "请输入同义词。", patternMaxLength: "模式不得超过256个字符。", synonymMaxLength: "同义词不得超过100个字符。", duplicatePattern: "已注册相同模式。", duplicateSynonym: "已注册同名同义词。", invalidRegexWithReason: "正则表达式“{value}”无效。{reason}", regexSyntaxError: "正则表达式语法错误：{reason}", maxPatterns: "最多可以注册5个模式。", patternCheckRequired: "请输入要检查的模式。", patternRequiredBeforeTest: "请先注册至少一个模式。", testTextRequired: "请输入测试句子。", atLeastOnePattern: "请注册至少一个模式。", invalidPattern: "正则表达式“{value}”无效。" },
  },
  ja: {
    valueCreateTitle: "エンティティ値を作成", valueEditTitle: "エンティティ値を編集", synonymSearch: "同義語を検索", synonymSearchPlaceholder: "同義語を検索してください。", add: "追加", synonymList: "同義語一覧", noSynonymSearchResults: "検索条件に一致する同義語がありません。", emptySynonyms: "同義語が登録されていません。", pattern: "パターン", regexCheck: "正規表現を確認", patternList: "パターン一覧", emptyPatterns: "パターンが登録されていません。", regexTest: "正規表現テスト", regexTestPlaceholder: "テストする文を入力してください。", test: "テスト", validRegex: "登録可能な正規表現です。", matchedPatterns: "一致するパターン：{patterns}", noMatchedPatterns: "一致するパターンがありません。",
    validation: { valueRequired: "エンティティ値を入力してください。", valueMaxLength: "エンティティ値は100文字以内で入力してください。", duplicateValue: "同じ名前のエンティティ値が登録されています。", patternRequired: "パターンを入力してください。", synonymRequired: "同義語を入力してください。", patternMaxLength: "パターンは256文字以内で入力してください。", synonymMaxLength: "同義語は100文字以内で入力してください。", duplicatePattern: "同じパターンが登録されています。", duplicateSynonym: "同じ名前の同義語が登録されています。", invalidRegexWithReason: "正規表現「{value}」が正しくありません。{reason}", regexSyntaxError: "正規表現の構文エラー：{reason}", maxPatterns: "パターンは最大5件まで登録できます。", patternCheckRequired: "確認するパターンを入力してください。", patternRequiredBeforeTest: "先にパターンを1件以上登録してください。", testTextRequired: "テストする文を入力してください。", atLeastOnePattern: "パターンを1件以上登録してください。", invalidPattern: "正規表現「{value}」が正しくありません。" },
  },
  vi: {
    valueCreateTitle: "Tạo giá trị thực thể", valueEditTitle: "Sửa giá trị thực thể", synonymSearch: "Tìm từ đồng nghĩa", synonymSearchPlaceholder: "Tìm từ đồng nghĩa.", add: "Thêm", synonymList: "Danh sách từ đồng nghĩa", noSynonymSearchResults: "Không có từ đồng nghĩa phù hợp với điều kiện tìm kiếm.", emptySynonyms: "Chưa đăng ký từ đồng nghĩa.", pattern: "Mẫu", regexCheck: "Kiểm tra biểu thức chính quy", patternList: "Danh sách mẫu", emptyPatterns: "Chưa đăng ký mẫu.", regexTest: "Kiểm thử biểu thức chính quy", regexTestPlaceholder: "Nhập câu để kiểm tra.", test: "Kiểm tra", validRegex: "Biểu thức chính quy này có thể đăng ký.", matchedPatterns: "Mẫu khớp: {patterns}", noMatchedPatterns: "Không có mẫu nào khớp.",
    validation: { valueRequired: "Nhập giá trị thực thể.", valueMaxLength: "Giá trị thực thể không được vượt quá 100 ký tự.", duplicateValue: "Đã có giá trị thực thể cùng tên.", patternRequired: "Nhập mẫu.", synonymRequired: "Nhập từ đồng nghĩa.", patternMaxLength: "Mẫu không được vượt quá 256 ký tự.", synonymMaxLength: "Từ đồng nghĩa không được vượt quá 100 ký tự.", duplicatePattern: "Mẫu này đã được đăng ký.", duplicateSynonym: "Đã có từ đồng nghĩa cùng tên.", invalidRegexWithReason: "Biểu thức chính quy '{value}' không hợp lệ. {reason}", regexSyntaxError: "Lỗi cú pháp biểu thức chính quy: {reason}", maxPatterns: "Có thể đăng ký tối đa 5 mẫu.", patternCheckRequired: "Nhập mẫu cần kiểm tra.", patternRequiredBeforeTest: "Trước tiên hãy đăng ký ít nhất một mẫu.", testTextRequired: "Nhập câu để kiểm tra.", atLeastOnePattern: "Đăng ký ít nhất một mẫu.", invalidPattern: "Biểu thức chính quy '{value}' không hợp lệ." },
  },
  fr: {
    valueCreateTitle: "Créer une valeur d’entité", valueEditTitle: "Modifier la valeur d’entité", synonymSearch: "Rechercher des synonymes", synonymSearchPlaceholder: "Rechercher des synonymes.", add: "Ajouter", synonymList: "Liste des synonymes", noSynonymSearchResults: "Aucun synonyme ne correspond aux critères de recherche.", emptySynonyms: "Aucun synonyme enregistré.", pattern: "Motif", regexCheck: "Vérifier l’expression régulière", patternList: "Liste des motifs", emptyPatterns: "Aucun motif enregistré.", regexTest: "Test d’expression régulière", regexTestPlaceholder: "Saisissez une phrase à tester.", test: "Tester", validRegex: "Cette expression régulière peut être enregistrée.", matchedPatterns: "Motifs correspondants : {patterns}", noMatchedPatterns: "Aucun motif correspondant.",
    validation: { valueRequired: "Saisissez une valeur d’entité.", valueMaxLength: "La valeur d’entité ne doit pas dépasser 100 caractères.", duplicateValue: "Une valeur d’entité portant le même nom existe déjà.", patternRequired: "Saisissez un motif.", synonymRequired: "Saisissez un synonyme.", patternMaxLength: "Le motif ne doit pas dépasser 256 caractères.", synonymMaxLength: "Le synonyme ne doit pas dépasser 100 caractères.", duplicatePattern: "Le même motif est déjà enregistré.", duplicateSynonym: "Un synonyme portant le même nom existe déjà.", invalidRegexWithReason: "L’expression régulière « {value} » est invalide. {reason}", regexSyntaxError: "Erreur de syntaxe de l’expression régulière : {reason}", maxPatterns: "Vous pouvez enregistrer jusqu’à 5 motifs.", patternCheckRequired: "Saisissez le motif à vérifier.", patternRequiredBeforeTest: "Enregistrez d’abord au moins un motif.", testTextRequired: "Saisissez une phrase à tester.", atLeastOnePattern: "Enregistrez au moins un motif.", invalidPattern: "L’expression régulière « {value} » est invalide." },
  },
  de: {
    valueCreateTitle: "Entitätswert erstellen", valueEditTitle: "Entitätswert bearbeiten", synonymSearch: "Synonyme suchen", synonymSearchPlaceholder: "Synonyme suchen.", add: "Hinzufügen", synonymList: "Synonymliste", noSynonymSearchResults: "Keine Synonyme entsprechen den Suchkriterien.", emptySynonyms: "Keine Synonyme registriert.", pattern: "Muster", regexCheck: "Regulären Ausdruck prüfen", patternList: "Musterliste", emptyPatterns: "Keine Muster registriert.", regexTest: "Test des regulären Ausdrucks", regexTestPlaceholder: "Geben Sie einen Testsatz ein.", test: "Testen", validRegex: "Dieser reguläre Ausdruck kann registriert werden.", matchedPatterns: "Übereinstimmende Muster: {patterns}", noMatchedPatterns: "Keine übereinstimmenden Muster.",
    validation: { valueRequired: "Geben Sie einen Entitätswert ein.", valueMaxLength: "Der Entitätswert darf höchstens 100 Zeichen lang sein.", duplicateValue: "Ein Entitätswert mit demselben Namen ist bereits registriert.", patternRequired: "Geben Sie ein Muster ein.", synonymRequired: "Geben Sie ein Synonym ein.", patternMaxLength: "Das Muster darf höchstens 256 Zeichen lang sein.", synonymMaxLength: "Das Synonym darf höchstens 100 Zeichen lang sein.", duplicatePattern: "Dasselbe Muster ist bereits registriert.", duplicateSynonym: "Ein Synonym mit demselben Namen ist bereits registriert.", invalidRegexWithReason: "Der reguläre Ausdruck „{value}“ ist ungültig. {reason}", regexSyntaxError: "Syntaxfehler im regulären Ausdruck: {reason}", maxPatterns: "Sie können bis zu 5 Muster registrieren.", patternCheckRequired: "Geben Sie das zu prüfende Muster ein.", patternRequiredBeforeTest: "Registrieren Sie zuerst mindestens ein Muster.", testTextRequired: "Geben Sie einen Testsatz ein.", atLeastOnePattern: "Registrieren Sie mindestens ein Muster.", invalidPattern: "Der reguläre Ausdruck „{value}“ ist ungültig." },
  },
} satisfies Record<SupportedLanguage, EntityValueDialogCatalog>;
export const ENTITY_EDITOR_CATALOGS = {
  ko: { ...ko, ...entityValueDialogCatalogs.ko, validation: { ...ko.validation, ...entityValueDialogCatalogs.ko.validation } },
  en: { ...en, ...entityValueDialogCatalogs.en, validation: { ...en.validation, ...entityValueDialogCatalogs.en.validation } },
  "zh-CN": { ...zh, ...entityValueDialogCatalogs["zh-CN"], validation: { ...zh.validation, ...entityValueDialogCatalogs["zh-CN"].validation } },
  ja: { ...ja, ...entityValueDialogCatalogs.ja, validation: { ...ja.validation, ...entityValueDialogCatalogs.ja.validation } },
  vi: { ...vi, ...entityValueDialogCatalogs.vi, validation: { ...vi.validation, ...entityValueDialogCatalogs.vi.validation } },
  fr: { ...fr, ...entityValueDialogCatalogs.fr, validation: { ...fr.validation, ...entityValueDialogCatalogs.fr.validation } },
  de: { ...de, ...entityValueDialogCatalogs.de, validation: { ...de.validation, ...entityValueDialogCatalogs.de.validation } },
} satisfies Record<SupportedLanguage, EntityEditorCatalog>;
export function formatEntityEditorText(template:string,values:Record<string,string|number>){return template.replace(/\{(\w+)\}/g,(_,key:string)=>String(values[key]??""));}
