import type { SupportedLanguage } from "@/lib/language";

export type EntityNameDialogCatalog = { createTitle:string; editTitle:string; close:string; entityName:string; cancel:string; saving:string; confirm:string; validation:{ noActiveVersion:string; required:string; duplicate:string; created:string; updated:string; saveFailed:string } };

export const ENTITY_NAME_DIALOG_CATALOGS = {
  ko:{createTitle:"개체명 추가",editTitle:"개체명 수정",close:"닫기",entityName:"개체명",cancel:"취소",saving:"저장 중...",confirm:"확인",validation:{noActiveVersion:"활성 버전이 없습니다.",required:"개체명을 입력해주세요.",duplicate:"이미 사용 중인 개체명입니다.",created:"개체명이 등록되었습니다.",updated:"개체명이 수정되었습니다.",saveFailed:"개체명을 저장하지 못했습니다."}},
  en:{createTitle:"Add Entity Name",editTitle:"Edit Entity Name",close:"Close",entityName:"Entity Name",cancel:"Cancel",saving:"Saving...",confirm:"Confirm",validation:{noActiveVersion:"No active version is available.",required:"Enter an entity name.",duplicate:"This entity name is already in use.",created:"The entity name was added.",updated:"The entity name was updated.",saveFailed:"Failed to save the entity name."}},
  "zh-CN":{createTitle:"添加实体名称",editTitle:"编辑实体名称",close:"关闭",entityName:"实体名称",cancel:"取消",saving:"保存中...",confirm:"确认",validation:{noActiveVersion:"没有活动版本。",required:"请输入实体名称。",duplicate:"该实体名称已被使用。",created:"实体名称已添加。",updated:"实体名称已更新。",saveFailed:"无法保存实体名称。"}},
  ja:{createTitle:"エンティティ名を追加",editTitle:"エンティティ名を編集",close:"閉じる",entityName:"エンティティ名",cancel:"キャンセル",saving:"保存中...",confirm:"確認",validation:{noActiveVersion:"有効なバージョンがありません。",required:"エンティティ名を入力してください。",duplicate:"このエンティティ名は既に使用されています。",created:"エンティティ名を追加しました。",updated:"エンティティ名を更新しました。",saveFailed:"エンティティ名を保存できませんでした。"}},
  vi:{createTitle:"Thêm tên thực thể",editTitle:"Sửa tên thực thể",close:"Đóng",entityName:"Tên thực thể",cancel:"Hủy",saving:"Đang lưu...",confirm:"Xác nhận",validation:{noActiveVersion:"Không có phiên bản đang hoạt động.",required:"Nhập tên thực thể.",duplicate:"Tên thực thể này đang được sử dụng.",created:"Đã thêm tên thực thể.",updated:"Đã cập nhật tên thực thể.",saveFailed:"Không thể lưu tên thực thể."}},
  fr:{createTitle:"Ajouter un nom d’entité",editTitle:"Modifier le nom d’entité",close:"Fermer",entityName:"Nom de l’entité",cancel:"Annuler",saving:"Enregistrement...",confirm:"Confirmer",validation:{noActiveVersion:"Aucune version active.",required:"Saisissez un nom d’entité.",duplicate:"Ce nom d’entité est déjà utilisé.",created:"Le nom d’entité a été ajouté.",updated:"Le nom d’entité a été modifié.",saveFailed:"Impossible d’enregistrer le nom d’entité."}},
  de:{createTitle:"Entitätsname hinzufügen",editTitle:"Entitätsname bearbeiten",close:"Schließen",entityName:"Entitätsname",cancel:"Abbrechen",saving:"Speichern...",confirm:"Bestätigen",validation:{noActiveVersion:"Keine aktive Version vorhanden.",required:"Geben Sie einen Entitätsnamen ein.",duplicate:"Dieser Entitätsname wird bereits verwendet.",created:"Der Entitätsname wurde hinzugefügt.",updated:"Der Entitätsname wurde aktualisiert.",saveFailed:"Entitätsname konnte nicht gespeichert werden."}},
} satisfies Record<SupportedLanguage, EntityNameDialogCatalog>;