import type { SupportedLanguage } from "@/lib/language";

export type EntityListCatalog = {
  summary: { intent: string; configure: string; entity: string; dictionary: string; evaluation: string; retraining: string; analysis: string };
  uploadResultTitle: string; uploadComplete: string; addedNames: string; addedValues: string; addedDetails: string;
  duplicateNames: string; duplicateValues: string; duplicateDetails: string; invalidDetails: string; maxPatterns: string;
  loadFailed: string; reloadFailed: string; saveFailed: string; deleteLoadFailed: string; deleteReferenced: string; deleteSuccess: string;
  noUploadable: string; uploadSuccess: string; uploadReadFailed: string; pageLoading: string; searchPlaceholder: string; filter: string;
  addName: string; entityMenu: string; uploadFile: string; downloadFile: string; totalCount: string; pageSize: string; selectedCount: string;
  delete: string; selectAll: string; columns: { category: string; name: string; value: string; updatedAt: string; updatedBy: string };
  selectRow: string; registerValue: string; noSearchResults: string; empty: string; uploadTitle: string; uploadDescription: string;
  uploadEncodingHelp: string; uploadHeaderHelp: string; uploadTypeHelp: string; uploadPatternHelp: string; example: string;
};

export const ENTITY_LIST_CATALOGS = {
  ko: {
    summary: { intent: "의도", configure: "구성", entity: "개체", dictionary: "사전", evaluation: "평가", retraining: "재학습", analysis: "분석" },
    uploadResultTitle: "업로드 결과", uploadComplete: "업로드가 완료되었습니다.", addedNames: "추가된 개체명", addedValues: "추가된 개체값", addedDetails: "추가된 동의어/패턴", duplicateNames: "중복된 개체명", duplicateValues: "중복된 개체값", duplicateDetails: "중복된 동의어/패턴", invalidDetails: "유형이 잘못되어 등록되지 않은 동의어/패턴", maxPatterns: "Max 값을 초과한 패턴",
    loadFailed: "개체 정보를 불러오지 못했습니다.", reloadFailed: "학습 결과를 다시 불러오지 못했습니다.", saveFailed: "개체 저장 중 오류가 발생했습니다.", deleteLoadFailed: "개체 삭제 전 버전 정보를 불러오지 못했습니다.", deleteReferenced: "'{name}' 사용자 개체는 {usages}에서 사용하고 있어 삭제할 수 없습니다.", deleteSuccess: "선택한 개체가 삭제되었습니다.", noUploadable: "업로드 가능한 개체가 없습니다.", uploadSuccess: "개체 업로드가 완료되었습니다.", uploadReadFailed: "개체 업로드 파일을 읽지 못했습니다.",
    pageLoading: "개체 화면을 불러오는 중입니다.", searchPlaceholder: "개체명, 개체값, 정규식 또는 패턴을 검색하세요.", filter: "필터", addName: "+ 개체명 추가", entityMenu: "개체 메뉴", uploadFile: "파일 업로드", downloadFile: "파일 다운로드", totalCount: "전체 {count}건", pageSize: "{count}개씩 보기", selectedCount: "{count}개 선택", delete: "삭제", selectAll: "전체 선택", columns: { category: "구분", name: "개체명", value: "개체값", updatedAt: "최종수정일시", updatedBy: "최종수정자" }, selectRow: "{name} 선택", registerValue: "개체값 등록", noSearchResults: "검색 조건에 맞는 개체가 없습니다.", empty: "등록된 개체가 없습니다. 먼저 개체를 추가해주세요.",
    uploadTitle: "파일 업로드", uploadDescription: "아래 버튼으로 양식(.txt)을 다운로드한 후 파일을 업로드하세요.", uploadEncodingHelp: "UTF-8 형식의 .txt/.csv 파일로 개체를 한 번에 업로드할 수 있습니다.", uploadHeaderHelp: "헤더는 `개체명,개체값,유형(S/P),상세` 형식을 사용하세요.", uploadTypeHelp: "`S`는 동의어형, `P`는 패턴형입니다.", uploadPatternHelp: "패턴형은 한 줄에 1개씩 입력하고 최대 5개까지 등록할 수 있습니다.", example: "예시",
  },
  en: {
    summary: { intent: "Intent", configure: "Configuration", entity: "Entity", dictionary: "Dictionary", evaluation: "Evaluation", retraining: "Retraining", analysis: "Analysis" },
    uploadResultTitle: "Upload Results", uploadComplete: "Upload completed.", addedNames: "Entity names added", addedValues: "Entity values added", addedDetails: "Synonyms/patterns added", duplicateNames: "Duplicate entity names", duplicateValues: "Duplicate entity values", duplicateDetails: "Duplicate synonyms/patterns", invalidDetails: "Synonyms/patterns excluded due to invalid type", maxPatterns: "Patterns exceeding the maximum",
    loadFailed: "Failed to load entity information.", reloadFailed: "Failed to reload training results.", saveFailed: "Failed to save entities.", deleteLoadFailed: "Failed to load the version before deleting entities.", deleteReferenced: "The user entity '{name}' cannot be deleted because it is used by {usages}.", deleteSuccess: "The selected entities were deleted.", noUploadable: "No uploadable entities were found.", uploadSuccess: "Entity upload completed.", uploadReadFailed: "Failed to read the entity upload file.",
    pageLoading: "Loading the entity screen.", searchPlaceholder: "Search by entity name, value, regular expression, or pattern.", filter: "Filter", addName: "+ Add Entity Name", entityMenu: "Entity menu", uploadFile: "Upload File", downloadFile: "Download File", totalCount: "Total {count}", pageSize: "{count} per page", selectedCount: "{count} selected", delete: "Delete", selectAll: "Select all", columns: { category: "Category", name: "Entity Name", value: "Entity Value", updatedAt: "Last Modified", updatedBy: "Modified By" }, selectRow: "Select {name}", registerValue: "Add entity value", noSearchResults: "No entities match the search criteria.", empty: "No entities are registered. Add an entity first.",
    uploadTitle: "Upload File", uploadDescription: "Download the .txt template below, complete it, and upload the file.", uploadEncodingHelp: "Upload entities in bulk with a UTF-8 encoded .txt/.csv file.", uploadHeaderHelp: "Use the header `개체명,개체값,유형(S/P),상세`.", uploadTypeHelp: "`S` is a synonym and `P` is a pattern.", uploadPatternHelp: "Enter one pattern per row, up to five patterns.", example: "Example",
  },
  "zh-CN": {
    summary: { intent: "意图", configure: "配置", entity: "实体", dictionary: "词典", evaluation: "评估", retraining: "重新训练", analysis: "分析" },
    uploadResultTitle: "上传结果", uploadComplete: "上传完成。", addedNames: "新增实体名称", addedValues: "新增实体值", addedDetails: "新增同义词/模式", duplicateNames: "重复实体名称", duplicateValues: "重复实体值", duplicateDetails: "重复同义词/模式", invalidDetails: "因类型无效而排除的同义词/模式", maxPatterns: "超过最大值的模式",
    loadFailed: "无法加载实体信息。", reloadFailed: "无法重新加载训练结果。", saveFailed: "保存实体时发生错误。", deleteLoadFailed: "删除实体前无法加载版本。", deleteReferenced: "用户实体“{name}”正被 {usages} 使用，无法删除。", deleteSuccess: "已删除所选实体。", noUploadable: "没有可上传的实体。", uploadSuccess: "实体上传完成。", uploadReadFailed: "无法读取实体上传文件。",
    pageLoading: "正在加载实体页面。", searchPlaceholder: "按实体名称、实体值、正则表达式或模式搜索。", filter: "筛选", addName: "+ 添加实体名称", entityMenu: "实体菜单", uploadFile: "上传文件", downloadFile: "下载文件", totalCount: "共 {count} 条", pageSize: "每页 {count} 条", selectedCount: "已选择 {count} 条", delete: "删除", selectAll: "全选", columns: { category: "分类", name: "实体名称", value: "实体值", updatedAt: "最后修改", updatedBy: "修改者" }, selectRow: "选择{name}", registerValue: "添加实体值", noSearchResults: "没有符合搜索条件的实体。", empty: "尚未注册实体。请先添加实体。",
    uploadTitle: "上传文件", uploadDescription: "请下载下方 .txt 模板，填写后上传。", uploadEncodingHelp: "可通过 UTF-8 编码的 .txt/.csv 文件批量上传实体。", uploadHeaderHelp: "请使用表头 `개체명,개체값,유형(S/P),상세`。", uploadTypeHelp: "`S` 表示同义词，`P` 表示模式。", uploadPatternHelp: "每行输入一个模式，最多五个。", example: "示例",
  },
  ja: {
    summary: { intent: "意図", configure: "構成", entity: "エンティティ", dictionary: "辞書", evaluation: "評価", retraining: "再学習", analysis: "分析" },
    uploadResultTitle: "アップロード結果", uploadComplete: "アップロードが完了しました。", addedNames: "追加したエンティティ名", addedValues: "追加したエンティティ値", addedDetails: "追加した同義語/パターン", duplicateNames: "重複エンティティ名", duplicateValues: "重複エンティティ値", duplicateDetails: "重複した同義語/パターン", invalidDetails: "型が不正で除外された同義語/パターン", maxPatterns: "上限を超えたパターン",
    loadFailed: "エンティティ情報を読み込めませんでした。", reloadFailed: "学習結果を再読み込みできませんでした。", saveFailed: "エンティティの保存に失敗しました。", deleteLoadFailed: "削除前にバージョンを読み込めませんでした。", deleteReferenced: "ユーザーエンティティ「{name}」は {usages} で使用中のため削除できません。", deleteSuccess: "選択したエンティティを削除しました。", noUploadable: "アップロード可能なエンティティがありません。", uploadSuccess: "エンティティのアップロードが完了しました。", uploadReadFailed: "アップロードファイルを読み込めませんでした。",
    pageLoading: "エンティティ画面を読み込んでいます。", searchPlaceholder: "エンティティ名、値、正規表現、パターンで検索します。", filter: "フィルター", addName: "+ エンティティ名を追加", entityMenu: "エンティティメニュー", uploadFile: "ファイルをアップロード", downloadFile: "ファイルをダウンロード", totalCount: "全 {count} 件", pageSize: "{count}件ずつ表示", selectedCount: "{count}件選択", delete: "削除", selectAll: "すべて選択", columns: { category: "区分", name: "エンティティ名", value: "エンティティ値", updatedAt: "最終更新日時", updatedBy: "最終更新者" }, selectRow: "{name}を選択", registerValue: "エンティティ値を追加", noSearchResults: "検索条件に一致するエンティティがありません。", empty: "登録されたエンティティがありません。先に追加してください。",
    uploadTitle: "ファイルをアップロード", uploadDescription: "下の .txt テンプレートをダウンロードし、入力後にアップロードしてください。", uploadEncodingHelp: "UTF-8の .txt/.csv ファイルでエンティティを一括アップロードできます。", uploadHeaderHelp: "ヘッダーは `개체명,개체값,유형(S/P),상세` を使用します。", uploadTypeHelp: "`S`は同義語、`P`はパターンです。", uploadPatternHelp: "1行に1パターン、最大5件まで入力できます。", example: "例",
  },
  vi: {
    summary: { intent: "Ý định", configure: "Cấu hình", entity: "Thực thể", dictionary: "Từ điển", evaluation: "Đánh giá", retraining: "Huấn luyện lại", analysis: "Phân tích" },
    uploadResultTitle: "Kết quả tải lên", uploadComplete: "Đã tải lên hoàn tất.", addedNames: "Tên thực thể đã thêm", addedValues: "Giá trị thực thể đã thêm", addedDetails: "Từ đồng nghĩa/mẫu đã thêm", duplicateNames: "Tên thực thể trùng", duplicateValues: "Giá trị thực thể trùng", duplicateDetails: "Từ đồng nghĩa/mẫu trùng", invalidDetails: "Từ đồng nghĩa/mẫu bị loại do sai loại", maxPatterns: "Mẫu vượt giới hạn",
    loadFailed: "Không thể tải thông tin thực thể.", reloadFailed: "Không thể tải lại kết quả huấn luyện.", saveFailed: "Không thể lưu thực thể.", deleteLoadFailed: "Không thể tải phiên bản trước khi xóa.", deleteReferenced: "Không thể xóa thực thể người dùng '{name}' vì đang được dùng tại {usages}.", deleteSuccess: "Đã xóa các thực thể đã chọn.", noUploadable: "Không có thực thể nào có thể tải lên.", uploadSuccess: "Đã tải thực thể lên.", uploadReadFailed: "Không thể đọc tệp tải lên thực thể.",
    pageLoading: "Đang tải màn hình thực thể.", searchPlaceholder: "Tìm theo tên, giá trị, biểu thức chính quy hoặc mẫu.", filter: "Bộ lọc", addName: "+ Thêm tên thực thể", entityMenu: "Menu thực thể", uploadFile: "Tải tệp lên", downloadFile: "Tải tệp xuống", totalCount: "Tổng {count}", pageSize: "{count} mỗi trang", selectedCount: "Đã chọn {count}", delete: "Xóa", selectAll: "Chọn tất cả", columns: { category: "Loại", name: "Tên thực thể", value: "Giá trị", updatedAt: "Sửa lần cuối", updatedBy: "Người sửa" }, selectRow: "Chọn {name}", registerValue: "Thêm giá trị thực thể", noSearchResults: "Không có thực thể phù hợp với điều kiện tìm kiếm.", empty: "Chưa có thực thể. Hãy thêm thực thể trước.",
    uploadTitle: "Tải tệp lên", uploadDescription: "Tải mẫu .txt bên dưới, điền dữ liệu rồi tải lên.", uploadEncodingHelp: "Tải nhiều thực thể bằng tệp .txt/.csv mã hóa UTF-8.", uploadHeaderHelp: "Sử dụng tiêu đề `개체명,개체값,유형(S/P),상세`.", uploadTypeHelp: "`S` là từ đồng nghĩa, `P` là mẫu.", uploadPatternHelp: "Nhập một mẫu mỗi dòng, tối đa năm mẫu.", example: "Ví dụ",
  },
  fr: {
    summary: { intent: "Intention", configure: "Configuration", entity: "Entité", dictionary: "Dictionnaire", evaluation: "Évaluation", retraining: "Réentraînement", analysis: "Analyse" },
    uploadResultTitle: "Résultats de l’import", uploadComplete: "Import terminé.", addedNames: "Noms d’entité ajoutés", addedValues: "Valeurs ajoutées", addedDetails: "Synonymes/motifs ajoutés", duplicateNames: "Noms en double", duplicateValues: "Valeurs en double", duplicateDetails: "Synonymes/motifs en double", invalidDetails: "Synonymes/motifs exclus pour type incorrect", maxPatterns: "Motifs dépassant la limite",
    loadFailed: "Impossible de charger les entités.", reloadFailed: "Impossible de recharger les résultats d’entraînement.", saveFailed: "Échec de l’enregistrement des entités.", deleteLoadFailed: "Impossible de charger la version avant la suppression.", deleteReferenced: "L’entité utilisateur « {name} » ne peut pas être supprimée car elle est utilisée par {usages}.", deleteSuccess: "Les entités sélectionnées ont été supprimées.", noUploadable: "Aucune entité importable.", uploadSuccess: "Import des entités terminé.", uploadReadFailed: "Impossible de lire le fichier d’entités.",
    pageLoading: "Chargement de l’écran des entités.", searchPlaceholder: "Rechercher par nom, valeur, expression régulière ou motif.", filter: "Filtrer", addName: "+ Ajouter un nom d’entité", entityMenu: "Menu des entités", uploadFile: "Importer un fichier", downloadFile: "Télécharger le fichier", totalCount: "Total {count}", pageSize: "{count} par page", selectedCount: "{count} sélectionnés", delete: "Supprimer", selectAll: "Tout sélectionner", columns: { category: "Catégorie", name: "Nom de l’entité", value: "Valeur", updatedAt: "Dernière modification", updatedBy: "Modifié par" }, selectRow: "Sélectionner {name}", registerValue: "Ajouter une valeur", noSearchResults: "Aucune entité ne correspond aux critères.", empty: "Aucune entité enregistrée. Ajoutez-en une d’abord.",
    uploadTitle: "Importer un fichier", uploadDescription: "Téléchargez le modèle .txt ci-dessous, complétez-le puis importez-le.", uploadEncodingHelp: "Importez plusieurs entités avec un fichier .txt/.csv encodé en UTF-8.", uploadHeaderHelp: "Utilisez l’en-tête `개체명,개체값,유형(S/P),상세`.", uploadTypeHelp: "`S` désigne un synonyme et `P` un motif.", uploadPatternHelp: "Saisissez un motif par ligne, jusqu’à cinq.", example: "Exemple",
  },
  de: {
    summary: { intent: "Intent", configure: "Konfiguration", entity: "Entität", dictionary: "Wörterbuch", evaluation: "Bewertung", retraining: "Nachtraining", analysis: "Analyse" },
    uploadResultTitle: "Upload-Ergebnis", uploadComplete: "Upload abgeschlossen.", addedNames: "Hinzugefügte Entitätsnamen", addedValues: "Hinzugefügte Werte", addedDetails: "Hinzugefügte Synonyme/Muster", duplicateNames: "Doppelte Entitätsnamen", duplicateValues: "Doppelte Werte", duplicateDetails: "Doppelte Synonyme/Muster", invalidDetails: "Wegen ungültigem Typ ausgeschlossene Synonyme/Muster", maxPatterns: "Muster über dem Maximum",
    loadFailed: "Entitätsinformationen konnten nicht geladen werden.", reloadFailed: "Trainingsergebnisse konnten nicht neu geladen werden.", saveFailed: "Entitäten konnten nicht gespeichert werden.", deleteLoadFailed: "Version konnte vor dem Löschen nicht geladen werden.", deleteReferenced: "Die Benutzerentität „{name}“ kann nicht gelöscht werden, da sie von {usages} verwendet wird.", deleteSuccess: "Die ausgewählten Entitäten wurden gelöscht.", noUploadable: "Keine hochladbaren Entitäten gefunden.", uploadSuccess: "Entitätsupload abgeschlossen.", uploadReadFailed: "Entitätsdatei konnte nicht gelesen werden.",
    pageLoading: "Entitätsansicht wird geladen.", searchPlaceholder: "Nach Name, Wert, regulärem Ausdruck oder Muster suchen.", filter: "Filter", addName: "+ Entitätsname hinzufügen", entityMenu: "Entitätsmenü", uploadFile: "Datei hochladen", downloadFile: "Datei herunterladen", totalCount: "Gesamt {count}", pageSize: "{count} pro Seite", selectedCount: "{count} ausgewählt", delete: "Löschen", selectAll: "Alle auswählen", columns: { category: "Kategorie", name: "Entitätsname", value: "Entitätswert", updatedAt: "Zuletzt geändert", updatedBy: "Geändert von" }, selectRow: "{name} auswählen", registerValue: "Entitätswert hinzufügen", noSearchResults: "Keine Entitäten entsprechen den Suchkriterien.", empty: "Keine Entitäten registriert. Fügen Sie zuerst eine hinzu.",
    uploadTitle: "Datei hochladen", uploadDescription: "Laden Sie die .txt-Vorlage unten herunter, füllen Sie sie aus und laden Sie sie hoch.", uploadEncodingHelp: "Mehrere Entitäten können mit einer UTF-8-codierten .txt/.csv-Datei hochgeladen werden.", uploadHeaderHelp: "Verwenden Sie die Kopfzeile `개체명,개체값,유형(S/P),상세`.", uploadTypeHelp: "`S` steht für Synonym, `P` für Muster.", uploadPatternHelp: "Ein Muster pro Zeile, maximal fünf Muster.", example: "Beispiel",
  },
} satisfies Record<SupportedLanguage, EntityListCatalog>;

export const ENTITY_TYPE_LABELS = {
  ko: { system: "시스템 개체", user: "사용자 개체" },
  en: { system: "System entity", user: "User entity" },
  "zh-CN": { system: "系统实体", user: "用户实体" },
  ja: { system: "システムエンティティ", user: "ユーザーエンティティ" },
  vi: { system: "Thực thể hệ thống", user: "Thực thể người dùng" },
  fr: { system: "Entité système", user: "Entité utilisateur" },
  de: { system: "Systementität", user: "Benutzerentität" },
} satisfies Record<SupportedLanguage, { system: string; user: string }>;
export function formatEntityListText(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}
